/*
 *   Copyright (c) 2024 Edward Boggis-Rolfe
 *   All rights reserved.
 */

#import "rpc/rpc_types.idl"

namespace websocket_demo
{
    namespace v1
    {
        struct envelope
        {
            uint64_t message_id;
            uint64_t message_type;
            std::vector<char> data;
        };

        struct request
        {
            rpc::encoding encoding; 
            uint64_t tag;
            uint64_t caller_zone_id;
            uint64_t destination_zone_id;
            uint64_t object_id;
            uint64_t interface_id;
            uint64_t method_id;
            std::vector<char> data;
            std::vector<rpc::back_channel_entry> back_channel;
        };

        struct response
        {
            uint64_t error;
            std::vector<char> data;
            std::vector<rpc::back_channel_entry> back_channel;
        };

        interface i_context_event
        {
            int piece(const std::string& piece);
        };

        [status=demo]
        interface i_calculator
        {
            [description="add"] int add(double first_val, double second_val, [out] double& response);
            [description="subtract"] int subtract(double first_val, double second_val, [out] double& response);
            [description="multiply"] int multiply(double first_val, double second_val, [out] double& response);
            [description="divide"] int divide(double first_val, double second_val, [out] double& response);

            int add_prompt(const std::string& prompt);
            // int get_piece([out] std::string& piece, [out] bool& complete);
            int set_callback(const rpc::shared_ptr<i_context_event>& event);
        };
    }
}