/*
 *   Copyright (c) 2026 Edward Boggis-Rolfe
 *   All rights reserved.
 */

#import "rpc/rpc_types.idl"

namespace calculator
{
    namespace v1
    {
        error calculator_error
        {
            [description = "A supplied calculator argument is invalid."]
            INVALID_ARGUMENT
        };

        [status=demo]
        interface i_calculator
        {
            [description="Add two integers."]
            calculator_error add(int a, int b, [out] int& sum);

            [description="Subtract two integers."]
            calculator_error subtract(int a, int b, [out] int& difference);

            [description="Multiply two integers."]
            calculator_error multiply(int a, int b, [out] int& product);

            [description="Divide two integers."]
            calculator_error divide(int a, int b, [out] int& quotient);
        };
    }
}
