typedef int error_code;

namespace outer
{
    namespace inner
    {
        [status = production] interface i_widget
        {
        };

        [status = production]
        struct widget_state
        {
            int count;
        };
    }
}
