/*
 *   Copyright (c) 2026 Edward Boggis-Rolfe
 *   All rights reserved.
 */

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <vector>

namespace canopy::security::attestation
{
    inline constexpr size_t aead_key_size = 32;
    inline constexpr size_t aead_nonce_size = 12;
    inline constexpr size_t aead_nonce_prefix_size = 4;

    enum class security_level
    {
        none,
        development,
        simulation,
        hardware_legacy,
        hardware
    };

    struct cmw
    {
        std::string media_type;
        std::string content_format;
        std::vector<uint8_t> payload;
    };

    struct identity
    {
        std::string enclave_id;
        std::string zone_id;
    };

    struct evidence_binding
    {
        // The identity that the backend Evidence is expected to prove.
        identity subject;
        // Per-handshake number generated by the caller. This is not a schema
        // version; it separates one handshake run from another.
        uint64_t transcript_id{0};
        // Fresh bytes chosen by the verifier side so Evidence cannot be replayed
        // from an earlier run.
        std::vector<uint8_t> nonce;
    };

    struct attestation_policy
    {
        bool send_local_evidence{true};
        bool require_peer_evidence{true};
        bool allow_unattested_peer{false};
        bool allow_development_evidence{true};
        security_level minimum_security_level{security_level::development};
        std::string required_backend_id;
    };

    struct attestation_verdict
    {
        bool accepted{false};
        std::string reason;
        std::string backend_id;
        security_level level{security_level::none};
        identity peer_identity;
    };

    struct security_context
    {
        bool established{false};
        bool local_evidence_sent{false};
        bool peer_attested{false};
        identity local_identity;
        identity peer_identity;
        std::string backend_id;
        security_level level{security_level::none};
        std::string session_id;
        uint64_t transcript_id{0};
        uint64_t session_epoch{1};
    };

    enum class route_attestation_status
    {
        unknown,
        handshaking,
        attested,
        unattested_allowed,
        failed
    };

    enum class route_attestation_action
    {
        allow,
        start_handshake,
        wait_for_handshake,
        reject
    };

    struct route_attestation_state
    {
        route_attestation_status status{route_attestation_status::unknown};
        std::optional<security_context> context;
        std::string failure_reason;
        uint64_t failure_epoch{0};
        // Transcript ids separate one route-attestation handshake run from the
        // next. They are route-owned rather than service-global because replay
        // and audit reasoning is scoped to the destination route/session domain.
        uint64_t next_transcript_id{1};
    };

    struct reference_route_policy_input
    {
        bool attestation_required{true};
        bool route_is_local{false};
        bool may_start_handshake{true};
        route_attestation_state state;
    };

    struct route_policy_decision
    {
        route_attestation_action action{route_attestation_action::reject};
        std::string reason;
    };

    struct peer_evidence_policy_decision
    {
        bool accepted{false};
        std::string reason;
    };

    enum class protected_rpc_direction
    {
        caller_to_destination,
        destination_to_caller
    };

    struct protected_key_scope
    {
        std::string session_id;
        identity caller_identity;
        identity destination_identity;
        protected_rpc_direction direction{protected_rpc_direction::caller_to_destination};
    };

    struct aead_key_material
    {
        aead_key_material() = default;
        aead_key_material(const aead_key_material&) = default;
        auto operator=(const aead_key_material&) -> aead_key_material& = default;
        aead_key_material(aead_key_material&&) noexcept = default;
        auto operator=(aead_key_material&&) noexcept -> aead_key_material& = default;
        ~aead_key_material();

        std::array<uint8_t, aead_key_size> key{};
        std::array<uint8_t, aead_nonce_prefix_size> nonce_prefix{};
        protected_key_scope scope;
        uint64_t session_epoch{0};
    };

    struct monotonic_counter_result
    {
        bool accepted{false};
        std::string reason;
        uint64_t counter{0};
    };

    class attestation_backend
    {
    public:
        virtual ~attestation_backend() = default;

        [[nodiscard]] virtual auto backend_id() const -> std::string = 0;
        [[nodiscard]] virtual auto level() const -> security_level = 0;
        [[nodiscard]] virtual auto produce_evidence(const evidence_binding& binding) const -> cmw = 0;
        [[nodiscard]] virtual auto verify_evidence(
            const cmw& evidence,
            const evidence_binding& expected_binding,
            const attestation_policy& policy) const -> attestation_verdict = 0;

        [[nodiscard]] virtual auto supports_verifier_challenge() const -> bool { return false; }

        [[nodiscard]] virtual auto make_verifier_challenge(const evidence_binding& binding) const -> std::optional<cmw>
        {
            (void)binding;
            return std::nullopt;
        }

        [[nodiscard]] virtual auto produce_evidence_for_challenge(
            const cmw& verifier_challenge,
            const evidence_binding& binding) const -> std::optional<cmw>
        {
            (void)verifier_challenge;
            (void)binding;
            return std::nullopt;
        }

        [[nodiscard]] virtual auto verify_evidence_for_challenge(
            const cmw& evidence,
            const cmw& verifier_challenge,
            const evidence_binding& expected_binding,
            const attestation_policy& policy) const -> attestation_verdict
        {
            (void)evidence;
            (void)verifier_challenge;
            (void)expected_binding;
            (void)policy;
            attestation_verdict verdict;
            verdict.reason = "attestation backend does not support verifier challenges";
            return verdict;
        }
    };

    // Numeric ordering used by policy checks. Higher ranks satisfy lower
    // minimum_security_level values.
    [[nodiscard]] auto security_level_rank(security_level level) noexcept -> int;

    // Stable string form used in KDF context and diagnostics.
    [[nodiscard]] auto security_level_name(security_level level) noexcept -> const char*;

    // Builds the route-session identifier shared by both sides of one
    // attestation handshake. The participant pair is sorted so caller/responder
    // order does not matter, and each identity component is length-framed before
    // it is fed into the readable string. If enclave_id is present, zone_id is
    // treated as subordinate metadata and is not part of the session key.
    [[nodiscard]] auto make_session_id(
        const identity& local,
        const identity& peer,
        uint64_t transcript_id) -> std::string;
} // namespace canopy::security::attestation
