/*
 *   Copyright (c) 2026 Edward Boggis-Rolfe
 *   All rights reserved.
 */

#include <array>
#include <cmath>
#include <cstdint>
#include <limits>
#include <map>
#include <string>
#include <vector>

#include <rpc/rpc.h>
#include <serialiser_test/test_types.h>

#include "gmock/gmock.h"
#include "gtest/gtest.h"

void rpc_log(int level, const char* str, size_t sz)
{
    std::string message(str, sz);
    switch (level)
    {
    case 0:
        printf("[TRACE] %s\n", message.c_str());
        break;
    case 1:
        printf("[DEBUG] %s\n", message.c_str());
        break;
    case 2:
        printf("[INFO] %s\n", message.c_str());
        break;
    case 3:
        printf("[WARN] %s\n", message.c_str());
        break;
    case 4:
        printf("[ERROR] %s\n", message.c_str());
        break;
    case 5:
        printf("[CRITICAL] %s\n", message.c_str());
        break;
    default:
        printf("[LOG %d] %s\n", level, message.c_str());
        break;
    }
}

// ============================================================
// Encoding tag types for TYPED_TEST_SUITE
//
// Four encoding tags correspond to the four rpc::encoding values.
// YAS tags work directly with any serialisable type (including raw
// scalars via the YAS library).  The protocol_buffers tag requires
// IDL-generated wrapper structs that carry protobuf_serialise /
// protobuf_deserialise member functions; those wrappers are defined
// in tests/idls/serialiser_test/test_types.idl.
// ============================================================

struct yas_binary_enc
{
    static constexpr rpc::encoding value = rpc::encoding::yas_binary;
    static constexpr const char* name = "yas_binary";

    template<typename T> static std::vector<uint8_t> serialise(const T& obj) { return rpc::to_yas_binary(obj); }

    template<typename T> static std::string deserialise(const rpc::byte_span& data, T& obj)
    {
        return rpc::from_yas_binary(data, obj);
    }
};

struct yas_compressed_binary_enc
{
    static constexpr rpc::encoding value = rpc::encoding::yas_compressed_binary;
    static constexpr const char* name = "yas_compressed_binary";

    template<typename T> static std::vector<uint8_t> serialise(const T& obj)
    {
        return rpc::to_compressed_yas_binary(obj);
    }

    template<typename T> static std::string deserialise(const rpc::byte_span& data, T& obj)
    {
        return rpc::from_yas_compressed_binary(data, obj);
    }
};

struct yas_json_enc
{
    static constexpr rpc::encoding value = rpc::encoding::yas_json;
    static constexpr const char* name = "yas_json";

    template<typename T> static std::vector<uint8_t> serialise(const T& obj) { return rpc::to_yas_json(obj); }

    template<typename T> static std::string deserialise(const rpc::byte_span& data, T& obj)
    {
        return rpc::from_yas_json(data, obj);
    }
};

struct protocol_buffers_enc
{
    static constexpr rpc::encoding value = rpc::encoding::protocol_buffers;
    static constexpr const char* name = "protocol_buffers";

    template<typename T> static std::vector<uint8_t> serialise(const T& obj) { return rpc::to_protobuf(obj); }

    template<typename T> static std::string deserialise(const rpc::byte_span& data, T& obj)
    {
        return rpc::from_protobuf(data, obj);
    }
};

// ============================================================
// IDL wrapper scalar suite – tests all four encodings including
// protocol_buffers, using the generated wrapper structs from
// tests/idls/serialiser_test/test_types.idl.
// Each wrapper holds a single scalar field named "value".
// ============================================================

using AllEncodings = ::testing::Types<yas_binary_enc, yas_compressed_binary_enc, yas_json_enc, protocol_buffers_enc>;

template<typename EncodingTag> class WrappedScalarSerialiserTest : public ::testing::Test
{
protected:
    // Roundtrip for IDL-generated wrapper structs with integer value fields.
    // operator== is generated by the IDL tool so equality works directly.
    template<typename Wrapper> void roundtrip_wrapper(Wrapper original)
    {
        auto serialized = EncodingTag::template serialise<Wrapper>(original);
        // Protocol buffers legitimately produces an empty buffer for all-zero structs
        // (default values are omitted); parsing empty bytes yields all-zero defaults.
        if (EncodingTag::value != rpc::encoding::protocol_buffers)
        {
            ASSERT_FALSE(serialized.empty()) << EncodingTag::name << ": serialised data is empty";
        }
        rpc::byte_span data(serialized);
        Wrapper deserialized{};
        auto error = EncodingTag::template deserialise<Wrapper>(data, deserialized);
        EXPECT_TRUE(error.empty()) << EncodingTag::name << ": deserialise error: " << error;
        EXPECT_TRUE(deserialized == original) << EncodingTag::name << ": roundtrip value mismatch";
    }
};

TYPED_TEST_SUITE(WrappedScalarSerialiserTest, AllEncodings);

// ---- int8_t ----
TYPED_TEST(WrappedScalarSerialiserTest, Int8Zero)
{
    this->roundtrip_wrapper(scalar_test::int8_holder{0});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int8Min)
{
    this->roundtrip_wrapper(scalar_test::int8_holder{std::numeric_limits<int8_t>::min()});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int8Max)
{
    this->roundtrip_wrapper(scalar_test::int8_holder{std::numeric_limits<int8_t>::max()});
}

// ---- uint8_t ----
TYPED_TEST(WrappedScalarSerialiserTest, UInt8Zero)
{
    this->roundtrip_wrapper(scalar_test::uint8_holder{0});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt8Max)
{
    this->roundtrip_wrapper(scalar_test::uint8_holder{std::numeric_limits<uint8_t>::max()});
}

// ---- int16_t ----
TYPED_TEST(WrappedScalarSerialiserTest, Int16Zero)
{
    this->roundtrip_wrapper(scalar_test::int16_holder{0});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int16Min)
{
    this->roundtrip_wrapper(scalar_test::int16_holder{std::numeric_limits<int16_t>::min()});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int16Max)
{
    this->roundtrip_wrapper(scalar_test::int16_holder{std::numeric_limits<int16_t>::max()});
}

// ---- uint16_t ----
TYPED_TEST(WrappedScalarSerialiserTest, UInt16Zero)
{
    this->roundtrip_wrapper(scalar_test::uint16_holder{0});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt16Max)
{
    this->roundtrip_wrapper(scalar_test::uint16_holder{std::numeric_limits<uint16_t>::max()});
}

// ---- int32_t ----
TYPED_TEST(WrappedScalarSerialiserTest, Int32Zero)
{
    this->roundtrip_wrapper(scalar_test::int32_holder{0});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int32Min)
{
    this->roundtrip_wrapper(scalar_test::int32_holder{std::numeric_limits<int32_t>::min()});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int32Max)
{
    this->roundtrip_wrapper(scalar_test::int32_holder{std::numeric_limits<int32_t>::max()});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int32Typical)
{
    this->roundtrip_wrapper(scalar_test::int32_holder{123456789});
}

// ---- uint32_t ----
TYPED_TEST(WrappedScalarSerialiserTest, UInt32Zero)
{
    this->roundtrip_wrapper(scalar_test::uint32_holder{0});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt32Max)
{
    this->roundtrip_wrapper(scalar_test::uint32_holder{std::numeric_limits<uint32_t>::max()});
}

// ---- int64_t ----
TYPED_TEST(WrappedScalarSerialiserTest, Int64Zero)
{
    this->roundtrip_wrapper(scalar_test::int64_holder{0});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int64Min)
{
    this->roundtrip_wrapper(scalar_test::int64_holder{std::numeric_limits<int64_t>::min()});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int64Max)
{
    this->roundtrip_wrapper(scalar_test::int64_holder{std::numeric_limits<int64_t>::max()});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int64Typical)
{
    this->roundtrip_wrapper(scalar_test::int64_holder{-9876543210LL});
}

// ---- uint64_t ----
TYPED_TEST(WrappedScalarSerialiserTest, UInt64Zero)
{
    this->roundtrip_wrapper(scalar_test::uint64_holder{0});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt64Max)
{
    this->roundtrip_wrapper(scalar_test::uint64_holder{std::numeric_limits<uint64_t>::max()});
}

// ---- __int128 ----
TYPED_TEST(WrappedScalarSerialiserTest, Int128Zero)
{
    this->roundtrip_wrapper(scalar_test::int128_holder{__int128{0}});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int128Positive)
{
    this->roundtrip_wrapper(scalar_test::int128_holder{__int128{1} << 100});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int128Negative)
{
    this->roundtrip_wrapper(scalar_test::int128_holder{-(__int128{1} << 100)});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int128Max)
{
    this->roundtrip_wrapper(scalar_test::int128_holder{static_cast<__int128>(static_cast<unsigned __int128>(-1) >> 1)});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int128Min)
{
    this->roundtrip_wrapper(scalar_test::int128_holder{static_cast<__int128>(static_cast<unsigned __int128>(1) << 127)});
}

// ---- unsigned __int128 ----
TYPED_TEST(WrappedScalarSerialiserTest, UInt128Zero)
{
    this->roundtrip_wrapper(scalar_test::uint128_holder{static_cast<unsigned __int128>(0)});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt128Typical)
{
    unsigned __int128 val = (static_cast<unsigned __int128>(0xDEADBEEFCAFEBABEULL) << 64) | 0x0123456789ABCDEFULL;
    this->roundtrip_wrapper(scalar_test::uint128_holder{val});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt128Max)
{
    this->roundtrip_wrapper(scalar_test::uint128_holder{static_cast<unsigned __int128>(-1)});
}

// ---- float ----
TYPED_TEST(WrappedScalarSerialiserTest, FloatZero)
{
    this->roundtrip_wrapper(scalar_test::float_holder{0.0f});
}
TYPED_TEST(WrappedScalarSerialiserTest, FloatMin)
{
    this->roundtrip_wrapper(scalar_test::float_holder{std::numeric_limits<float>::lowest()});
}
TYPED_TEST(WrappedScalarSerialiserTest, FloatMax)
{
    this->roundtrip_wrapper(scalar_test::float_holder{std::numeric_limits<float>::max()});
}
TYPED_TEST(WrappedScalarSerialiserTest, FloatSmallest)
{
    this->roundtrip_wrapper(scalar_test::float_holder{std::numeric_limits<float>::min()});
}
TYPED_TEST(WrappedScalarSerialiserTest, FloatTypical)
{
    this->roundtrip_wrapper(scalar_test::float_holder{3.14159265f});
}
TYPED_TEST(WrappedScalarSerialiserTest, FloatNegative)
{
    this->roundtrip_wrapper(scalar_test::float_holder{-2.71828182f});
}

// ---- double ----
TYPED_TEST(WrappedScalarSerialiserTest, DoubleZero)
{
    this->roundtrip_wrapper(scalar_test::double_holder{0.0});
}
TYPED_TEST(WrappedScalarSerialiserTest, DoubleMin)
{
    this->roundtrip_wrapper(scalar_test::double_holder{std::numeric_limits<double>::lowest()});
}
TYPED_TEST(WrappedScalarSerialiserTest, DoubleMax)
{
    this->roundtrip_wrapper(scalar_test::double_holder{std::numeric_limits<double>::max()});
}
TYPED_TEST(WrappedScalarSerialiserTest, DoubleSmallest)
{
    this->roundtrip_wrapper(scalar_test::double_holder{std::numeric_limits<double>::min()});
}
TYPED_TEST(WrappedScalarSerialiserTest, DoubleTypical)
{
    this->roundtrip_wrapper(scalar_test::double_holder{3.14159265358979323846});
}
TYPED_TEST(WrappedScalarSerialiserTest, DoubleNegative)
{
    this->roundtrip_wrapper(scalar_test::double_holder{-2.71828182845904523536});
}

// ============================================================
// String, vector and array holder tests — all four encodings
// ============================================================

// ---- std::string ----
TYPED_TEST(WrappedScalarSerialiserTest, StringEmpty)
{
    this->roundtrip_wrapper(scalar_test::string_holder{""});
}
TYPED_TEST(WrappedScalarSerialiserTest, StringTypical)
{
    this->roundtrip_wrapper(scalar_test::string_holder{"hello, world!"});
}
TYPED_TEST(WrappedScalarSerialiserTest, StringUnicode)
{
    this->roundtrip_wrapper(scalar_test::string_holder{"\xc3\xa9\xc3\xa0\xc3\xbc"});
}

// ---- std::vector<T> ----
TYPED_TEST(WrappedScalarSerialiserTest, Int8VecEmpty)
{
    this->roundtrip_wrapper(scalar_test::int8_vec_holder{{}});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int8VecTypical)
{
    this->roundtrip_wrapper(
        scalar_test::int8_vec_holder{{std::numeric_limits<int8_t>::min(), -1, 0, 1, std::numeric_limits<int8_t>::max()}});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt8VecTypical)
{
    this->roundtrip_wrapper(scalar_test::uint8_vec_holder{{0, 1, 127, std::numeric_limits<uint8_t>::max()}});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int16VecTypical)
{
    this->roundtrip_wrapper(
        scalar_test::int16_vec_holder{{std::numeric_limits<int16_t>::min(), -1, 0, std::numeric_limits<int16_t>::max()}});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt16VecTypical)
{
    this->roundtrip_wrapper(scalar_test::uint16_vec_holder{{0, 1, 1000, std::numeric_limits<uint16_t>::max()}});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int32VecTypical)
{
    this->roundtrip_wrapper(
        scalar_test::int32_vec_holder{{std::numeric_limits<int32_t>::min(), -1, 0, std::numeric_limits<int32_t>::max()}});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt32VecTypical)
{
    this->roundtrip_wrapper(scalar_test::uint32_vec_holder{{0, 1, 123456, std::numeric_limits<uint32_t>::max()}});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int64VecTypical)
{
    this->roundtrip_wrapper(scalar_test::int64_vec_holder{
        {std::numeric_limits<int64_t>::min(), -1LL, 0LL, std::numeric_limits<int64_t>::max()}});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt64VecTypical)
{
    this->roundtrip_wrapper(scalar_test::uint64_vec_holder{{0ULL, 1ULL, 42ULL, std::numeric_limits<uint64_t>::max()}});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int128VecTypical)
{
    scalar_test::int128_vec_holder h;
    h.value = {__int128{0},
        -(__int128{1} << 100),
        __int128{1} << 100,
        static_cast<__int128>(static_cast<unsigned __int128>(-1) >> 1)};
    this->roundtrip_wrapper(h);
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt128VecTypical)
{
    scalar_test::uint128_vec_holder h;
    h.value = {static_cast<unsigned __int128>(0),
        (static_cast<unsigned __int128>(0xDEADBEEFULL) << 64) | 0xCAFEBABEULL,
        static_cast<unsigned __int128>(-1)};
    this->roundtrip_wrapper(h);
}
TYPED_TEST(WrappedScalarSerialiserTest, FloatVecTypical)
{
    this->roundtrip_wrapper(scalar_test::float_vec_holder{
        {std::numeric_limits<float>::lowest(), -1.0f, 0.0f, std::numeric_limits<float>::max()}});
}
TYPED_TEST(WrappedScalarSerialiserTest, DoubleVecTypical)
{
    this->roundtrip_wrapper(scalar_test::double_vec_holder{
        {std::numeric_limits<double>::lowest(), -1.0, 0.0, std::numeric_limits<double>::max()}});
}
TYPED_TEST(WrappedScalarSerialiserTest, StringVecTypical)
{
    this->roundtrip_wrapper(scalar_test::string_vec_holder{{"", "hello", "world", "test"}});
}

// ---- std::array<T, 4> ----
TYPED_TEST(WrappedScalarSerialiserTest, Int8ArrTypical)
{
    this->roundtrip_wrapper(
        scalar_test::int8_arr_holder{{{std::numeric_limits<int8_t>::min(), -1, 0, std::numeric_limits<int8_t>::max()}}});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt8ArrTypical)
{
    this->roundtrip_wrapper(scalar_test::uint8_arr_holder{{{0, 1, 127, std::numeric_limits<uint8_t>::max()}}});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int16ArrTypical)
{
    this->roundtrip_wrapper(scalar_test::int16_arr_holder{
        {{std::numeric_limits<int16_t>::min(), -1, 0, std::numeric_limits<int16_t>::max()}}});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt16ArrTypical)
{
    this->roundtrip_wrapper(scalar_test::uint16_arr_holder{{{0, 1, 1000, std::numeric_limits<uint16_t>::max()}}});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int32ArrTypical)
{
    this->roundtrip_wrapper(scalar_test::int32_arr_holder{
        {{std::numeric_limits<int32_t>::min(), -1, 0, std::numeric_limits<int32_t>::max()}}});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt32ArrTypical)
{
    this->roundtrip_wrapper(scalar_test::uint32_arr_holder{{{0, 1, 123456, std::numeric_limits<uint32_t>::max()}}});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int64ArrTypical)
{
    this->roundtrip_wrapper(scalar_test::int64_arr_holder{
        {{std::numeric_limits<int64_t>::min(), -1LL, 0LL, std::numeric_limits<int64_t>::max()}}});
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt64ArrTypical)
{
    this->roundtrip_wrapper(scalar_test::uint64_arr_holder{{{0ULL, 1ULL, 42ULL, std::numeric_limits<uint64_t>::max()}}});
}
TYPED_TEST(WrappedScalarSerialiserTest, Int128ArrTypical)
{
    scalar_test::int128_arr_holder h;
    h.value = {__int128{0},
        -(__int128{1} << 100),
        __int128{1} << 100,
        static_cast<__int128>(static_cast<unsigned __int128>(-1) >> 1)};
    this->roundtrip_wrapper(h);
}
TYPED_TEST(WrappedScalarSerialiserTest, UInt128ArrTypical)
{
    scalar_test::uint128_arr_holder h;
    h.value = {static_cast<unsigned __int128>(0),
        (static_cast<unsigned __int128>(0xDEADBEEFULL) << 64) | 0xCAFEBABEULL,
        static_cast<unsigned __int128>(-1),
        static_cast<unsigned __int128>(1) << 64};
    this->roundtrip_wrapper(h);
}
TYPED_TEST(WrappedScalarSerialiserTest, FloatArrTypical)
{
    this->roundtrip_wrapper(scalar_test::float_arr_holder{
        {{std::numeric_limits<float>::lowest(), -1.0f, 0.0f, std::numeric_limits<float>::max()}}});
}
TYPED_TEST(WrappedScalarSerialiserTest, DoubleArrTypical)
{
    this->roundtrip_wrapper(scalar_test::double_arr_holder{
        {{std::numeric_limits<double>::lowest(), -1.0, 0.0, std::numeric_limits<double>::max()}}});
}
TYPED_TEST(WrappedScalarSerialiserTest, StringArrTypical)
{
    this->roundtrip_wrapper(scalar_test::string_arr_holder{{{"", "hello", "world", "test"}}});
}

// ============================================================
// IDL struct serialisation tests covering all four encodings
// including protocol_buffers (requires generated protobuf members)
// ============================================================

class SerialiserTest : public ::testing::Test
{
protected:
    void SetUp() override { }

    void TearDown() override { }
};

// Test to_yas_json serialization with generated structure
TEST_F(SerialiserTest, ToYasJson)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "test_string";

    auto result = rpc::to_yas_json(obj);

    EXPECT_FALSE(result.empty());
    EXPECT_NE(result[0], '\0');
}

// Test to_yas_binary serialization with generated structure
TEST_F(SerialiserTest, ToYasBinary)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "test_string";

    auto result = rpc::to_yas_binary(obj);

    EXPECT_FALSE(result.empty());
}

// Test to_compressed_yas_binary serialization with generated structure
TEST_F(SerialiserTest, ToCompressedYasBinary)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "test_string";

    auto result = rpc::to_compressed_yas_binary(obj);

    EXPECT_FALSE(result.empty());
}

// Test to_protobuf serialization with generated structure
TEST_F(SerialiserTest, ToProtobuf)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "test";

    auto result = rpc::to_protobuf(obj);

    EXPECT_FALSE(result.empty());
    EXPECT_GT(result.size(), 0u);
}

// Test from_yas_json deserialization with generated structure
TEST_F(SerialiserTest, FromYasJson)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "test_string";

    auto serialized = rpc::to_yas_json(obj);
    rpc::byte_span data_span(serialized);

    scalar_test::something_complicated deserialized;
    auto error = rpc::from_yas_json(data_span, deserialized);

    EXPECT_TRUE(error.empty());
    EXPECT_EQ(deserialized.int_val, 42);
    EXPECT_EQ(deserialized.string_val, "test_string");
}

// Test from_yas_binary deserialization with generated structure
TEST_F(SerialiserTest, FromYasBinary)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "test_string";

    auto serialized = rpc::to_yas_binary(obj);
    rpc::byte_span data_span(serialized);

    scalar_test::something_complicated deserialized;
    auto error = rpc::from_yas_binary(data_span, deserialized);

    EXPECT_TRUE(error.empty());
    EXPECT_EQ(deserialized.int_val, 42);
    EXPECT_EQ(deserialized.string_val, "test_string");
}

// Test from_yas_compressed_binary deserialization with generated structure
TEST_F(SerialiserTest, FromYasCompressedBinary)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "test_string";

    auto serialized = rpc::to_compressed_yas_binary(obj);
    rpc::byte_span data_span(serialized);

    scalar_test::something_complicated deserialized;
    auto error = rpc::from_yas_compressed_binary(data_span, deserialized);

    EXPECT_TRUE(error.empty());
    EXPECT_EQ(deserialized.int_val, 42);
    EXPECT_EQ(deserialized.string_val, "test_string");
}

// Test from_protobuf deserialization with generated structure
TEST_F(SerialiserTest, FromProtobuf)
{
    scalar_test::something_complicated obj;
    obj.int_val = 100;
    obj.string_val = "hello";

    auto serialized = rpc::to_protobuf(obj);
    rpc::byte_span data_span(serialized);

    scalar_test::something_complicated deserialized;
    auto error = rpc::from_protobuf(data_span, deserialized);

    EXPECT_TRUE(error.empty());
    EXPECT_EQ(deserialized.int_val, 100);
    EXPECT_EQ(deserialized.string_val, "hello");
}

// Test serialise function with all encodings using generated structure
TEST_F(SerialiserTest, SerialiseAllEncodings)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "serialize_test";

    auto json_result = rpc::serialise(obj, rpc::encoding::yas_json);
    EXPECT_FALSE(json_result.empty());

    auto binary_result = rpc::serialise(obj, rpc::encoding::yas_binary);
    EXPECT_FALSE(binary_result.empty());

    auto compressed_result = rpc::serialise(obj, rpc::encoding::yas_compressed_binary);
    EXPECT_FALSE(compressed_result.empty());

    auto protobuf_result = rpc::serialise(obj, rpc::encoding::protocol_buffers);
    EXPECT_FALSE(protobuf_result.empty());
}

// Test deserialise function with all encodings using generated structure
TEST_F(SerialiserTest, DeserialiseAllEncodings)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "deserialize_test";

    {
        auto serialized = rpc::serialise(obj, rpc::encoding::yas_json);
        rpc::byte_span data_span(serialized);
        scalar_test::something_complicated deserialized;
        auto error = rpc::deserialise(rpc::encoding::yas_json, data_span, deserialized);
        EXPECT_TRUE(error.empty());
        EXPECT_EQ(deserialized.int_val, obj.int_val);
        EXPECT_EQ(deserialized.string_val, obj.string_val);
    }

    {
        auto serialized = rpc::serialise(obj, rpc::encoding::yas_binary);
        rpc::byte_span data_span(serialized);
        scalar_test::something_complicated deserialized;
        auto error = rpc::deserialise(rpc::encoding::yas_binary, data_span, deserialized);
        EXPECT_TRUE(error.empty());
        EXPECT_EQ(deserialized.int_val, obj.int_val);
        EXPECT_EQ(deserialized.string_val, obj.string_val);
    }

    {
        auto serialized = rpc::serialise(obj, rpc::encoding::yas_compressed_binary);
        rpc::byte_span data_span(serialized);
        scalar_test::something_complicated deserialized;
        auto error = rpc::deserialise(rpc::encoding::yas_compressed_binary, data_span, deserialized);
        EXPECT_TRUE(error.empty());
        EXPECT_EQ(deserialized.int_val, obj.int_val);
        EXPECT_EQ(deserialized.string_val, obj.string_val);
    }

    {
        auto serialized = rpc::serialise(obj, rpc::encoding::protocol_buffers);
        rpc::byte_span data_span(serialized);
        scalar_test::something_complicated deserialized;
        auto error = rpc::deserialise(rpc::encoding::protocol_buffers, data_span, deserialized);
        EXPECT_TRUE(error.empty());
        EXPECT_EQ(deserialized.int_val, obj.int_val);
        EXPECT_EQ(deserialized.string_val, obj.string_val);
    }
}

// Test get_saved_size function with all encodings
TEST_F(SerialiserTest, GetSavedSizeAllEncodings)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "size_test";

    auto json_size = rpc::get_saved_size(obj, rpc::encoding::yas_json);
    EXPECT_GT(json_size, 0u);

    auto binary_size = rpc::get_saved_size(obj, rpc::encoding::yas_binary);
    EXPECT_GT(binary_size, 0u);

    auto compressed_size = rpc::get_saved_size(obj, rpc::encoding::yas_compressed_binary);
    EXPECT_GT(compressed_size, 0u);

    auto protobuf_size = rpc::get_saved_size(obj, rpc::encoding::protocol_buffers);
    EXPECT_GT(protobuf_size, 0u);

    auto json_result = rpc::serialise(obj, rpc::encoding::yas_json);
    EXPECT_EQ(json_size, json_result.size());

    auto binary_result = rpc::serialise(obj, rpc::encoding::yas_binary);
    EXPECT_EQ(binary_size, binary_result.size());

    auto protobuf_result = rpc::serialise(obj, rpc::encoding::protocol_buffers);
    EXPECT_EQ(protobuf_size, protobuf_result.size());
}

// Test with complex structure
TEST_F(SerialiserTest, ComplexStructProtobuf)
{
    scalar_test::something_complicated obj;
    obj.int_val = 123;
    obj.string_val = "complex_test";

    auto serialized = rpc::serialise(obj, rpc::encoding::protocol_buffers);
    EXPECT_FALSE(serialized.empty());

    rpc::byte_span data_span(serialized);
    scalar_test::something_complicated deserialized;
    auto error = rpc::from_protobuf(data_span, deserialized);

    EXPECT_TRUE(error.empty());
    EXPECT_EQ(deserialized.int_val, 123);
    EXPECT_EQ(deserialized.string_val, "complex_test");
}

// Test with nested structure
TEST_F(SerialiserTest, NestedStructProtobuf)
{
    scalar_test::something_more_complicated obj;
    obj.vector_val.push_back({1, "first"});
    obj.vector_val.push_back({2, "second"});
    obj.map_val["key1"] = {FLD(int_val) 10, FLD(string_val) "map_first"};
    obj.map_val["key2"] = {FLD(int_val) 20, FLD(string_val) "map_second"};

    auto serialized = rpc::serialise(obj, rpc::encoding::protocol_buffers);
    EXPECT_FALSE(serialized.empty());

    rpc::byte_span data_span(serialized);
    scalar_test::something_more_complicated deserialized;
    auto error = rpc::from_protobuf(data_span, deserialized);

    EXPECT_TRUE(error.empty());
    EXPECT_EQ(deserialized.vector_val.size(), 2u);
    EXPECT_EQ(deserialized.map_val.size(), 2u);
}

// Test roundtrip for all encodings with generated structure
TEST_F(SerialiserTest, RoundtripAllEncodings)
{
    scalar_test::something_complicated original;
    original.int_val = 999;
    original.string_val = "roundtrip_test";

    const std::vector<rpc::encoding> encodings = {rpc::encoding::yas_json,
        rpc::encoding::yas_binary,
        rpc::encoding::yas_compressed_binary,
        rpc::encoding::protocol_buffers};

    for (auto enc : encodings)
    {
        auto serialized = rpc::serialise(original, enc);
        EXPECT_FALSE(serialized.empty()) << "Serialization failed for encoding: " << static_cast<int>(enc);

        rpc::byte_span data_span(serialized);
        scalar_test::something_complicated deserialized;
        auto error = rpc::deserialise(enc, data_span, deserialized);
        EXPECT_TRUE(error.empty()) << "Deserialization failed for encoding: " << static_cast<int>(enc)
                                   << " error: " << error;
        EXPECT_EQ(deserialized.int_val, original.int_val) << "int_val mismatch for encoding: " << static_cast<int>(enc);
        EXPECT_EQ(deserialized.string_val, original.string_val)
            << "string_val mismatch for encoding: " << static_cast<int>(enc);
    }
}

// Test with template structure
TEST_F(SerialiserTest, TemplateStructProtobuf)
{
    scalar_test::test_template<int> obj;
    obj.type_t = 42;

    auto serialized = rpc::serialise(obj, rpc::encoding::protocol_buffers);
    EXPECT_FALSE(serialized.empty());

    rpc::byte_span data_span(serialized);
    scalar_test::test_template<int> deserialized;
    auto error = rpc::from_protobuf(data_span, deserialized);

    EXPECT_TRUE(error.empty());
    EXPECT_EQ(deserialized.type_t, 42);
}

// Test protobuf_saved_size function
TEST_F(SerialiserTest, ProtobufSavedSize)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "test";

    auto size = rpc::protobuf_saved_size(obj);
    EXPECT_GT(size, 0u);

    auto serialized = rpc::to_protobuf(obj);
    EXPECT_EQ(size, serialized.size());
}

// Test edge cases - empty string
TEST_F(SerialiserTest, EmptyStringProtobuf)
{
    scalar_test::something_complicated obj;
    obj.int_val = 0;
    obj.string_val = "";

    auto serialized = rpc::to_protobuf(obj);
    rpc::byte_span data_span(serialized);

    scalar_test::something_complicated deserialized;
    auto error = rpc::from_protobuf(data_span, deserialized);

    EXPECT_TRUE(error.empty());
    EXPECT_EQ(deserialized.int_val, 0);
    EXPECT_EQ(deserialized.string_val, "");
}

// Test edge cases - large values
TEST_F(SerialiserTest, LargeValuesProtobuf)
{
    scalar_test::something_complicated obj;
    obj.int_val = INT_MAX;
    obj.string_val = std::string(1000, 'x');

    auto serialized = rpc::to_protobuf(obj);
    rpc::byte_span data_span(serialized);

    scalar_test::something_complicated deserialized;
    auto error = rpc::from_protobuf(data_span, deserialized);

    EXPECT_TRUE(error.empty());
    EXPECT_EQ(deserialized.int_val, INT_MAX);
    EXPECT_EQ(deserialized.string_val, std::string(1000, 'x'));
}

// Test to_yas_json with std::array
TEST_F(SerialiserTest, ToYasJsonWithArray)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "test_string";

    auto json_result = rpc::to_yas_json<std::array<char, 200>>(obj);
    EXPECT_FALSE(json_result.empty());

    EXPECT_THROW((rpc::to_yas_json<std::array<char, 10>>(obj)), std::runtime_error);
}

// Test to_yas_binary with std::array
TEST_F(SerialiserTest, ToYasBinaryWithArray)
{
    scalar_test::something_complicated obj;
    obj.int_val = 42;
    obj.string_val = "test_string";

    auto binary_result = rpc::to_yas_binary<std::array<char, 200>>(obj);
    EXPECT_FALSE(binary_result.empty());

    EXPECT_THROW((rpc::to_yas_binary<std::array<char, 10>>(obj)), std::runtime_error);
}
