#!/usr/bin/env python3
#
# Copyright (c) 2026 Edward Boggis-Rolfe
# All rights reserved.

"""Generate offline REST caller-to-handler round-trip tests.

The generated tests deliberately do not contact the upstream provider.  They wire
the generated REST caller to the generated REST handler through an in-process
HTTP loopback stream, with a small rpc::base implementation behind the handler.
That checks that the Swagger-derived IDL and .rest.json agree for outgoing and
incoming URL cracking, body marshalling, and RPC dispatch.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REST_ROOT = ROOT / "third_party_interfaces" / "rest"
GENERATED_MARKER = "Generated by tools/generate_rest_roundtrip_tests.py"
BEGIN_CMAKE_MARKER = "# BEGIN generated by tools/generate_rest_roundtrip_tests.py"
END_CMAKE_MARKER = "# END generated by tools/generate_rest_roundtrip_tests.py"
ROUNDTRIP_NS = "canopy::third_party_rest::roundtrip"


@dataclass
class RestMethod:
    name: str
    http_method: str
    path: str
    body_param: str
    out_param: str


@dataclass
class RestMetadata:
    qualified_interface: str = ""
    host: str = ""
    base_path: str = ""
    methods: dict[str, RestMethod] = field(default_factory=dict)


@dataclass
class IdlParameter:
    direction: str
    declaration: str
    type_name: str
    value_type: str
    name: str


@dataclass
class IdlMethod:
    return_type: str
    name: str
    parameters: list[IdlParameter]
    const_suffix: bool = False


@dataclass
class EndpointInfo:
    slug: str
    target: str
    idl_path: Path
    binding_path: Path
    include_path: str
    metadata: RestMetadata
    methods: list[IdlMethod]
    defined_types: set[str] = field(default_factory=set)
    global_types: set[str] = field(default_factory=set)


def split_top_level(value: str, delimiter: str = ",") -> list[str]:
    parts: list[str] = []
    start = 0
    angle_depth = 0
    paren_depth = 0
    square_depth = 0
    for index, ch in enumerate(value):
        if ch == "<":
            angle_depth += 1
        elif ch == ">" and angle_depth:
            angle_depth -= 1
        elif ch == "(":
            paren_depth += 1
        elif ch == ")" and paren_depth:
            paren_depth -= 1
        elif ch == "[":
            square_depth += 1
        elif ch == "]" and square_depth:
            square_depth -= 1
        elif ch == delimiter and angle_depth == 0 and paren_depth == 0 and square_depth == 0:
            parts.append(value[start:index].strip())
            start = index + 1
    tail = value[start:].strip()
    if tail:
        parts.append(tail)
    return parts


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//.*", "", text)


def matching_brace(text: str, open_index: int) -> int:
    depth = 0
    for index in range(open_index, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return index
    raise ValueError("unterminated interface block")


def normalise_type_for_value(type_name: str) -> str:
    value = re.sub(r"\bconst\b", "", type_name)
    value = value.replace("&", "").replace("*", "")
    value = re.sub(r"\s+", " ", value).strip()
    return value


def parse_parameter(raw: str) -> IdlParameter:
    direction_match = re.search(r"\[(in|out)\]", raw)
    if not direction_match:
        raise ValueError(f"parameter direction missing: {raw}")
    direction = direction_match.group(1)
    declaration = re.sub(r"\[[^\]]+\]\s*", "", raw).strip()
    declaration = re.sub(r"\s*=.*$", "", declaration).strip()
    name_match = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*$", declaration)
    if not name_match:
        raise ValueError(f"parameter name missing: {raw}")
    name = name_match.group(1)
    type_name = declaration[: name_match.start()].strip()
    return IdlParameter(
        direction=direction,
        declaration=declaration,
        type_name=type_name,
        value_type=normalise_type_for_value(type_name),
        name=name,
    )


def parse_idl_methods(idl_path: Path, qualified_interface: str) -> list[IdlMethod]:
    text = strip_comments(idl_path.read_text(encoding="utf-8", errors="replace"))
    interface_name = qualified_interface.split("::")[-1]
    match = re.search(rf"\binterface\s+{re.escape(interface_name)}\s*\{{", text)
    if not match:
        raise ValueError(f"interface {qualified_interface} not found")
    open_brace = text.find("{", match.start())
    close_brace = matching_brace(text, open_brace)
    body = text[open_brace + 1 : close_brace]

    methods: list[IdlMethod] = []
    for declaration in split_top_level(body, ";"):
        declaration = re.sub(r"^\s*(\[[^\]]+\]\s*)+", "", declaration.strip())
        if not declaration or "(" not in declaration or ")" not in declaration:
            continue
        open_paren = declaration.find("(")
        close_paren = declaration.rfind(")")
        prefix = declaration[:open_paren].strip()
        suffix = declaration[close_paren + 1 :].strip()
        name_match = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*$", prefix)
        if not name_match:
            continue
        name = name_match.group(1)
        return_type = prefix[: name_match.start()].strip()
        parameter_text = declaration[open_paren + 1 : close_paren].strip()
        parameters = [parse_parameter(item) for item in split_top_level(parameter_text)] if parameter_text else []
        methods.append(IdlMethod(return_type=return_type, name=name, parameters=parameters, const_suffix=suffix == "const"))
    return methods


def collect_idl_type_names(idl_path: Path) -> tuple[set[str], set[str]]:
    text = strip_comments(idl_path.read_text(encoding="utf-8", errors="replace"))
    defined_types = set(re.findall(r"\bstruct\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{", text))
    global_types = set(re.findall(r"\btypedef\b[^;]*\b([A-Za-z_][A-Za-z0-9_]*)\s*;", text))
    return defined_types, global_types


def parse_json_binding(path: Path) -> RestMetadata:
    value = json.loads(path.read_text(encoding="utf-8"))
    interfaces = value.get("interfaces")
    if not isinstance(interfaces, list) or not interfaces:
        raise ValueError(f"REST binding has no interfaces: {path}")
    interface = interfaces[0]
    result = RestMetadata(
        qualified_interface=interface.get("qualified_name", ""),
        host=interface.get("host", ""),
        base_path=interface.get("base_path", ""),
    )
    for method in interface.get("methods", []):
        request = method.get("request") or {}
        response = method.get("response") or {}
        name = method.get("name", "")
        if not name:
            continue
        result.methods[name] = RestMethod(
            name=name,
            http_method=method.get("http_method", ""),
            path=method.get("path", ""),
            body_param=request.get("body_param", ""),
            out_param=response.get("out_param", ""),
        )
    if not result.qualified_interface:
        raise ValueError(f"REST binding has no interface name: {path}")
    return result


def parse_rest_binding(path: Path) -> RestMetadata:
    if path.name.endswith(".rest.json"):
        return parse_json_binding(path)
    raise ValueError(f"expected .rest.json binding: {path}")


def target_from_idl_cmake(endpoint_root: Path, fallback: str) -> str:
    cmake_path = endpoint_root / "idl" / "CMakeLists.txt"
    if not cmake_path.exists():
        return fallback
    match = re.search(r"CanopyGenerate\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)", cmake_path.read_text(encoding="utf-8"))
    return match.group(1) if match else fallback


def endpoint_from_binding(binding_path: Path) -> EndpointInfo:
    endpoint_root = binding_path.parents[2]
    if binding_path.name.endswith(".rest.json"):
        idl_path = binding_path.with_name(binding_path.name[: -len(".rest.json")] + ".idl")
    else:
        raise ValueError(f"unexpected REST binding filename: {binding_path}")
    target = target_from_idl_cmake(endpoint_root, idl_path.stem)
    metadata = parse_rest_binding(binding_path)
    if not metadata.methods:
        raise ValueError("skip_no_methods")
    methods = parse_idl_methods(idl_path, metadata.qualified_interface)
    include_path = f"{idl_path.parent.name}/{idl_path.stem}.h"
    defined_types, global_types = collect_idl_type_names(idl_path)
    return EndpointInfo(
        slug=endpoint_root.name,
        target=target,
        idl_path=idl_path,
        binding_path=binding_path,
        include_path=include_path,
        metadata=metadata,
        methods=methods,
        defined_types=defined_types,
        global_types=global_types,
    )


def cxx_string(value: str) -> str:
    return json.dumps(value)


def write_if_different(path: Path, content: str) -> None:
    old = None
    try:
        old = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        pass
    if old == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def namespace_parts(qualified_interface: str) -> list[str]:
    return qualified_interface.split("::")[:-1]


def open_namespaces(parts: list[str]) -> str:
    return "".join(f"namespace {part}\n{{\n" for part in parts)


def close_namespaces(parts: list[str]) -> str:
    return "".join(f"}} // namespace {part}\n" for part in reversed(parts))


def parameter_list(method: IdlMethod) -> str:
    return ", ".join(parameter.declaration for parameter in method.parameters)


def method_argument_setup(method: IdlMethod) -> tuple[list[str], list[str]]:
    lines: list[str] = []
    args: list[str] = []
    for parameter in method.parameters:
        if parameter.direction == "in":
            lines.append(f"        auto {parameter.name} = {ROUNDTRIP_NS}::sample_value<{parameter.value_type}>();")
        else:
            lines.append(f"        {parameter.value_type} {parameter.name}{{}};")
        args.append(parameter.name)
    return lines, args


def qualify_generated_type(
    type_name: str, namespace_prefix: str, defined_types: set[str], global_types: set[str]
) -> str:
    if (not namespace_prefix or not defined_types) and not global_types:
        return type_name

    def replace(match: re.Match[str]) -> str:
        token = match.group(0)
        before = type_name[: match.start()]
        after = type_name[match.end() :]
        if before.endswith("::") or after.startswith("::"):
            return token
        if token in global_types:
            return f"::{token}"
        if token not in defined_types or not namespace_prefix:
            return token
        return f"::{namespace_prefix}::{token}"

    return re.sub(r"\b[A-Za-z_][A-Za-z0-9_]*\b", replace, type_name)


def method_argument_setup_for_main(
    method: IdlMethod, namespace_prefix: str, defined_types: set[str], global_types: set[str]
) -> tuple[list[str], list[str]]:
    lines: list[str] = []
    args: list[str] = []
    for parameter in method.parameters:
        value_type = qualify_generated_type(parameter.value_type, namespace_prefix, defined_types, global_types)
        if parameter.direction == "in":
            lines.append(f"        auto {parameter.name} = {ROUNDTRIP_NS}::sample_value<{value_type}>();")
        else:
            lines.append(f"        {value_type} {parameter.name}{{}};")
        args.append(parameter.name)
    return lines, args


def unique_local_name(base_name: str, method: IdlMethod) -> str:
    used_names = {parameter.name for parameter in method.parameters}
    if base_name not in used_names:
        return base_name

    suffix = 1
    while f"{base_name}_{suffix}" in used_names:
        suffix += 1
    return f"{base_name}_{suffix}"


def write_source(info: EndpointInfo, output_path: Path) -> None:
    ns_parts = namespace_parts(info.metadata.qualified_interface)
    namespace_prefix = "::".join(ns_parts)
    interface_simple = info.metadata.qualified_interface.split("::")[-1]
    interface_type = f"::{info.metadata.qualified_interface}"
    service_type = (
        f"::{namespace_prefix}::roundtrip_recording_service" if namespace_prefix else "::roundtrip_recording_service"
    )
    methods_by_name = {method.name: method for method in info.methods}
    callable_methods = [methods_by_name[name] for name in info.metadata.methods if name in methods_by_name]

    if not callable_methods:
        raise ValueError(f"no metadata methods matched IDL methods for {info.slug}")

    service_methods: list[str] = []
    for method in info.methods:
        params = parameter_list(method)
        const_suffix = " const" if method.const_suffix else ""
        body: list[str] = []
        if method.name in info.metadata.methods:
            body.append(f"        recorded_methods.push_back({cxx_string(method.name)});")
        for parameter in method.parameters:
            if parameter.direction == "out":
                body.append(f"        {parameter.name} = {ROUNDTRIP_NS}::sample_value<{parameter.value_type}>();")
            else:
                body.append(f"        (void){parameter.name};")
        if method.return_type == "void":
            body.append("        CO_RETURN;")
        else:
            return_type = qualify_generated_type(method.return_type, namespace_prefix, info.defined_types, info.global_types)
            body.append(f"        CO_RETURN {ROUNDTRIP_NS}::ok_return<{return_type}>();")
        service_methods.append(
            f"    CORO_TASK({method.return_type}) {method.name}({params}){const_suffix} override\n"
            "    {\n"
            + "\n".join(body)
            + "\n    }\n"
        )

    call_blocks: list[str] = []
    expected_calls: list[str] = []
    for method in callable_methods:
        setup_lines, args = method_argument_setup_for_main(
            method, namespace_prefix, info.defined_types, info.global_types
        )
        call_result_name = unique_local_name("call_result", method)
        result_check = (
            f"        const auto {call_result_name} = SYNC_WAIT(connected.object->{method.name}({', '.join(args)}));\n"
            f"        if (static_cast<int>({call_result_name}) != rpc::error::OK())\n"
            "        {\n"
            f"            std::cerr << {cxx_string(method.name)} << \" failed: \" << static_cast<int>({call_result_name}) << \"\\n\";\n"
            "            if (client.stream)\n"
            f"                {ROUNDTRIP_NS}::print_last_exchange(std::cerr, *client.stream);\n"
            "            return 4;\n"
            "        }"
            if method.return_type != "void"
            else f"        SYNC_WAIT(connected.object->{method.name}({', '.join(args)}));"
        )
        call_blocks.append(
            "    {\n"
            + ("\n".join(setup_lines) + "\n" if setup_lines else "")
            + result_check
            + "\n    }\n"
        )
        expected_calls.append(method.name)

    source = f"""// {GENERATED_MARKER}

#include <iostream>
#include <string>
#include <utility>
#include <vector>

#include <canopy/third_party_rest/roundtrip_test_support.h>
#include <canopy/rest/server.h>
#include <rpc/rpc.h>

#include <{info.include_path}>

{open_namespaces(ns_parts)}
class roundtrip_recording_service final : public rpc::base<roundtrip_recording_service, {interface_simple}>
{{
public:
    std::vector<std::string> recorded_methods;

{''.join(service_methods)}
}};
{close_namespaces(ns_parts)}

int main()
{{
    using interface_type = {interface_type};
    using service_type = {service_type};
    auto implementation = new service_type;
    rpc::shared_ptr<interface_type> object(implementation);

    canopy::rest::endpoint_registry registry;
    registry.add_object<interface_type>("roundtrip", object);
    auto client = {ROUNDTRIP_NS}::make_loopback_client<interface_type>(
        std::move(registry), {cxx_string(info.target + "_roundtrip_loopback")});

    auto connected = SYNC_WAIT(
        interface_type::rest_caller::connect(std::move(client.settings), {{}}, std::move(client.factory_context)));
    if (connected.error_code != rpc::error::OK() || !connected.object)
    {{
        std::cerr << "connect failed: " << connected.error_code << "\\n";
        return 3;
    }}

{''.join(call_blocks)}
    const std::vector<std::string> expected_methods{{{', '.join(cxx_string(name) for name in expected_calls)}}};
    if (implementation->recorded_methods != expected_methods)
    {{
        std::cerr << "recorded method mismatch: expected " << expected_methods.size()
                  << " calls, got " << implementation->recorded_methods.size() << "\\n";
        return 5;
    }}

    if (connected.stream)
        SYNC_WAIT(connected.stream->set_closed());
    connected.object = nullptr;
    connected.stream.reset();

    std::cout << "roundtrip ok: {info.slug} ({len(expected_calls)} methods)\\n";
    return 0;
}}
"""
    write_if_different(output_path, source)


def cmake_block(info: EndpointInfo) -> str:
    target = info.target
    test_target = f"{target}_roundtrip_test"
    return f"""{BEGIN_CMAKE_MARKER}
if((DEFINED CANOPY_BUILD_TEST AND CANOPY_BUILD_TEST) OR (DEFINED BUILD_TEST AND BUILD_TEST))
  add_executable({test_target} src/{test_target}.cpp)
  target_compile_definitions({test_target} PRIVATE ${{CANOPY_DEFINES}})
  target_include_directories({test_target} PRIVATE ${{CANOPY_INCLUDES}} ${{CMAKE_CURRENT_LIST_DIR}}/../include)
  target_compile_options({test_target} PRIVATE ${{CANOPY_COMPILE_OPTIONS}} ${{CANOPY_WARN_OK}})
  target_link_options({test_target} PRIVATE ${{CANOPY_LINK_EXE_OPTIONS}})
  target_link_libraries(
    {test_target}
    PRIVATE {target}_idl
            json_idl
            rest
            rpc::modules
            rpc
            rpc_log
            ${{CANOPY_LIBRARIES}})
  set_property(GLOBAL APPEND PROPERTY CANOPY_THIRD_PARTY_REST_ROUNDTRIP_TEST_TARGETS {test_target})
  add_test(NAME {test_target} COMMAND {test_target})
endif()
{END_CMAKE_MARKER}
"""


def ensure_endpoint_idl_cmake(info: EndpointInfo) -> None:
    idl_root = info.binding_path.parents[1]
    cmake_path = idl_root / "CMakeLists.txt"
    if cmake_path.exists():
        return

    content = f"""cmake_minimum_required(VERSION 3.24)

# Generated by tools/generate_rest_roundtrip_tests.py
CanopyGenerate(
  {info.target}
  {info.idl_path.parent.name}/{info.idl_path.name}
  ${{CMAKE_CURRENT_LIST_DIR}}
  ${{CMAKE_BINARY_DIR}}/generated
  ""
  yas_binary
  yas_json
  rest_client ${{CMAKE_CURRENT_LIST_DIR}}/{info.binding_path.parent.name}/{info.idl_path.stem}.openapi.json
  dependencies rpc_types_idl json_idl
  include_paths ${{CMAKE_CURRENT_LIST_DIR}} ${{CANOPY_INTERFACE_SOURCE_DIR}}
  install_dir ${{GENERATED_INSTALL_DIR}})
"""
    write_if_different(cmake_path, content)


def update_endpoint_cmake(info: EndpointInfo) -> None:
    cmake_path = info.binding_path.parents[2] / "CMakeLists.txt"
    text = cmake_path.read_text(encoding="utf-8") if cmake_path.exists() else "cmake_minimum_required(VERSION 3.24)\n\nadd_subdirectory(idl)\n"
    block = cmake_block(info)
    pattern = re.compile(re.escape(BEGIN_CMAKE_MARKER) + r".*?" + re.escape(END_CMAKE_MARKER) + r"\n?", re.S)
    if pattern.search(text):
        text = pattern.sub(block, text)
    else:
        if not text.endswith("\n"):
            text += "\n"
        text += "\n" + block
    write_if_different(cmake_path, text)


def discover_bindings(rest_root: Path, slugs: list[str]) -> list[Path]:
    def endpoint_bindings(endpoint_root: Path) -> list[Path]:
        return sorted(endpoint_root.glob("idl/*/*.rest.json"))

    if slugs:
        paths: list[Path] = []
        for slug in slugs:
            paths.extend(endpoint_bindings(rest_root / slug))
        return paths
    paths = []
    for endpoint_root in sorted(path for path in rest_root.iterdir() if path.is_dir()):
        paths.extend(endpoint_bindings(endpoint_root))
    return paths


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rest-root", type=Path, default=REST_ROOT)
    parser.add_argument("--manifest", type=Path, default=None)
    parser.add_argument("--slug", action="append", default=[])
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    rest_root = args.rest_root.resolve()
    manifest_path = (args.manifest or rest_root / "roundtrip_manifest.json").resolve()
    entries = []
    for binding_path in discover_bindings(rest_root, args.slug):
        entry = {"slug": binding_path.parents[2].name, "rest_binding": str(binding_path)}
        try:
            info = endpoint_from_binding(binding_path)
            source_path = binding_path.parents[2] / "src" / f"{info.target}_roundtrip_test.cpp"
            entry.update(
                {
                    "status": "dry_run" if args.dry_run else "written",
                    "target": info.target,
                    "test_target": f"{info.target}_roundtrip_test",
                    "test_source": str(source_path),
                    "qualified_interface": info.metadata.qualified_interface,
                    "methods": len(info.metadata.methods),
                    "http_methods": sorted({method.http_method.upper() for method in info.metadata.methods.values()}),
                }
            )
            if not args.dry_run:
                ensure_endpoint_idl_cmake(info)
                write_source(info, source_path)
                update_endpoint_cmake(info)
        except Exception as exc:
            if str(exc) == "skip_no_methods":
                entry.update({"status": "skipped_no_methods", "methods": 0, "http_methods": []})
            else:
                entry.update({"status": "failed", "error": str(exc)})
        entries.append(entry)

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    method_counts = Counter()
    for entry in entries:
        if entry.get("status") not in ("written", "dry_run"):
            continue
        for method in entry.get("http_methods", []):
            method_counts[method] += 1
    write_if_different(
        manifest_path,
        json.dumps({"http_method_endpoint_coverage": dict(sorted(method_counts.items())), "entries": entries}, indent=2)
        + "\n",
    )
    written = sum(1 for entry in entries if entry["status"] in ("written", "dry_run"))
    failed = sum(1 for entry in entries if entry["status"] == "failed")
    skipped = sum(1 for entry in entries if entry["status"] == "skipped_no_methods")
    coverage = ", ".join(f"{method}={count}" for method, count in sorted(method_counts.items()))
    print(f"roundtrip generation: {written} usable, {skipped} skipped, {failed} failed; manifest: {manifest_path}")
    if coverage:
        print(f"http method endpoint coverage: {coverage}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
