#!/usr/bin/env python3
#
# Copyright (c) 2026 Edward Boggis-Rolfe
# All rights reserved.

"""Generate offline REST caller-to-handler round-trip tests.

The generated tests deliberately do not contact the upstream provider.  They wire
the generated REST caller to the generated REST handler through an in-process
HTTP loopback stream, with a small rpc::base implementation behind the handler.
That checks that the Swagger-derived IDL and .rest.json agree for outgoing and
incoming URL cracking, body marshalling, and RPC dispatch.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REST_ROOT = ROOT / "third_party_interfaces" / "rest"
GENERATED_MARKER = "Generated by tools/generate_rest_roundtrip_tests.py"
BEGIN_CMAKE_MARKER = "# BEGIN generated by tools/generate_rest_roundtrip_tests.py"
END_CMAKE_MARKER = "# END generated by tools/generate_rest_roundtrip_tests.py"
ROUNDTRIP_NS = "canopy::third_party_rest::roundtrip"


@dataclass
class RestField:
    name: str
    wire_name: str
    required: bool


@dataclass
class RestMethod:
    name: str
    http_method: str
    path: str
    body_param: str
    out_param: str
    request_schema_json: str = ""
    request_value_schema_json: str = ""
    response_schema_json: str = ""
    response_value_schema_json: str = ""
    source_response_schema_json: str = ""
    response_content_type: str = ""
    response_fields: list[RestField] = field(default_factory=list)


@dataclass
class RestMetadata:
    qualified_interface: str = ""
    host: str = ""
    base_path: str = ""
    methods: dict[str, RestMethod] = field(default_factory=dict)


@dataclass
class IdlParameter:
    direction: str
    declaration: str
    type_name: str
    value_type: str
    name: str


@dataclass
class IdlMethod:
    return_type: str
    name: str
    parameters: list[IdlParameter]
    const_suffix: bool = False


@dataclass
class EndpointInfo:
    slug: str
    target: str
    idl_path: Path
    binding_path: Path
    include_path: str
    metadata: RestMetadata
    methods: list[IdlMethod]
    defined_types: set[str] = field(default_factory=set)
    global_types: set[str] = field(default_factory=set)


def split_top_level(value: str, delimiter: str = ",") -> list[str]:
    parts: list[str] = []
    start = 0
    angle_depth = 0
    paren_depth = 0
    square_depth = 0
    for index, ch in enumerate(value):
        if ch == "<":
            angle_depth += 1
        elif ch == ">" and angle_depth:
            angle_depth -= 1
        elif ch == "(":
            paren_depth += 1
        elif ch == ")" and paren_depth:
            paren_depth -= 1
        elif ch == "[":
            square_depth += 1
        elif ch == "]" and square_depth:
            square_depth -= 1
        elif ch == delimiter and angle_depth == 0 and paren_depth == 0 and square_depth == 0:
            parts.append(value[start:index].strip())
            start = index + 1
    tail = value[start:].strip()
    if tail:
        parts.append(tail)
    return parts


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//.*", "", text)


def matching_brace(text: str, open_index: int) -> int:
    depth = 0
    for index in range(open_index, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return index
    raise ValueError("unterminated interface block")


def normalise_type_for_value(type_name: str) -> str:
    value = re.sub(r"\bconst\b", "", type_name)
    value = value.replace("&", "").replace("*", "")
    value = re.sub(r"\s+", " ", value).strip()
    return value


def parse_parameter(raw: str) -> IdlParameter:
    direction_match = re.search(r"\[(in|out)\]", raw)
    if not direction_match:
        raise ValueError(f"parameter direction missing: {raw}")
    direction = direction_match.group(1)
    declaration = re.sub(r"\[[^\]]+\]\s*", "", raw).strip()
    declaration = re.sub(r"\s*=.*$", "", declaration).strip()
    name_match = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*$", declaration)
    if not name_match:
        raise ValueError(f"parameter name missing: {raw}")
    name = name_match.group(1)
    type_name = declaration[: name_match.start()].strip()
    return IdlParameter(
        direction=direction,
        declaration=declaration,
        type_name=type_name,
        value_type=normalise_type_for_value(type_name),
        name=name,
    )


def parse_idl_methods(idl_path: Path, qualified_interface: str) -> list[IdlMethod]:
    text = strip_comments(idl_path.read_text(encoding="utf-8", errors="replace"))
    interface_name = qualified_interface.split("::")[-1]
    match = re.search(rf"\binterface\s+{re.escape(interface_name)}\s*\{{", text)
    if not match:
        raise ValueError(f"interface {qualified_interface} not found")
    open_brace = text.find("{", match.start())
    close_brace = matching_brace(text, open_brace)
    body = text[open_brace + 1 : close_brace]

    methods: list[IdlMethod] = []
    for declaration in split_top_level(body, ";"):
        declaration = re.sub(r"^\s*(\[[^\]]+\]\s*)+", "", declaration.strip())
        if not declaration or "(" not in declaration or ")" not in declaration:
            continue
        open_paren = declaration.find("(")
        close_paren = declaration.rfind(")")
        prefix = declaration[:open_paren].strip()
        suffix = declaration[close_paren + 1 :].strip()
        name_match = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*$", prefix)
        if not name_match:
            continue
        name = name_match.group(1)
        return_type = prefix[: name_match.start()].strip()
        parameter_text = declaration[open_paren + 1 : close_paren].strip()
        parameters = [parse_parameter(item) for item in split_top_level(parameter_text)] if parameter_text else []
        methods.append(IdlMethod(return_type=return_type, name=name, parameters=parameters, const_suffix=suffix == "const"))
    return methods


def collect_idl_type_names(idl_path: Path) -> tuple[set[str], set[str]]:
    text = strip_comments(idl_path.read_text(encoding="utf-8", errors="replace"))
    defined_types = set(re.findall(r"\bstruct\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{", text))
    global_types = set(re.findall(r"\btypedef\b[^;]*\b([A-Za-z_][A-Za-z0-9_]*)\s*;", text))
    return defined_types, global_types


def resolve_local_ref(document: dict, ref: str) -> object:
    if not ref.startswith("#/"):
        raise KeyError(ref)
    value: object = document
    for part in ref[2:].split("/"):
        part = part.replace("~1", "/").replace("~0", "~")
        if not isinstance(value, dict):
            raise KeyError(ref)
        value = value[part]
    return value


def source_openapi_path(binding_path: Path, binding: dict) -> Path | None:
    source = binding.get("source")
    if not isinstance(source, dict):
        return None
    openapi = source.get("openapi")
    if not isinstance(openapi, str) or not openapi:
        return None
    path = Path(openapi)
    if not path.is_absolute():
        path = binding_path.parent / path
    return path if path.exists() else None


def load_source_spec(binding_path: Path, binding: dict) -> dict:
    path = source_openapi_path(binding_path, binding)
    if path is None:
        return {}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return value if isinstance(value, dict) else {}


def response_schema_from_content(content: object) -> dict | None:
    if not isinstance(content, dict):
        return None
    for media_type in ("application/json", "application/*+json", "*/*"):
        media = content.get(media_type)
        if isinstance(media, dict) and isinstance(media.get("schema"), dict):
            return media["schema"]
    for media in content.values():
        if isinstance(media, dict) and isinstance(media.get("schema"), dict):
            return media["schema"]
    return None


def source_response_schema(source_spec: dict, http_method: str, path: str) -> dict | None:
    paths = source_spec.get("paths")
    if not isinstance(paths, dict):
        return None
    path_item = paths.get(path)
    if not isinstance(path_item, dict):
        return None
    operation = path_item.get(http_method.lower())
    if not isinstance(operation, dict):
        return None
    responses = operation.get("responses")
    if not isinstance(responses, dict):
        return None

    for status, response in sorted(responses.items(), key=lambda item: (0 if str(item[0]).startswith("2") else 1, str(item[0]))):
        status_text = str(status)
        if not status_text.startswith("2") or status_text in {"204", "205"}:
            continue
        if isinstance(response, dict) and isinstance(response.get("$ref"), str):
            try:
                response = resolve_local_ref(source_spec, response["$ref"])
            except (KeyError, TypeError):
                return None
        if not isinstance(response, dict):
            return None
        if isinstance(response.get("schema"), dict):
            return response["schema"]
        schema = response_schema_from_content(response.get("content"))
        if schema is not None:
            return schema
    return None


def schema_document_with_refs(source_spec: dict, schema: dict) -> dict:
    document = copy.deepcopy(schema)
    for key in ("components", "definitions"):
        value = source_spec.get(key)
        if isinstance(value, dict) and key not in document:
            document[key] = copy.deepcopy(value)
    return document


def parse_json_binding(path: Path) -> RestMetadata:
    value = json.loads(path.read_text(encoding="utf-8"))
    source_spec = load_source_spec(path, value)
    interfaces = value.get("interfaces")
    if not isinstance(interfaces, list) or not interfaces:
        raise ValueError(f"REST binding has no interfaces: {path}")
    interface = interfaces[0]
    result = RestMetadata(
        qualified_interface=interface.get("qualified_name", ""),
        host=interface.get("host", ""),
        base_path=interface.get("base_path", ""),
    )
    for method in interface.get("methods", []):
        request = method.get("request") or {}
        response = method.get("response") or {}
        name = method.get("name", "")
        if not name:
            continue
        request_schema = request.get("body_schema")
        response_schema = response.get("body_schema")
        original_response_schema = source_response_schema(source_spec, method.get("http_method", ""), method.get("path", ""))
        request_field_map = parse_body_field_map(request.get("body_field_map"))
        response_field_map = parse_body_field_map(response.get("body_field_map"))
        response_fields = [
            RestField(
                name=field.get("name", ""),
                wire_name=field.get("wire_name", field.get("name", "")),
                required=bool(field.get("required", True)),
            )
            for field in response.get("fields", [])
            if isinstance(field, dict) and field.get("name")
        ]
        result.methods[name] = RestMethod(
            name=name,
            http_method=method.get("http_method", ""),
            path=method.get("path", ""),
            body_param=request.get("body_param", ""),
            out_param=response.get("out_param", ""),
            request_schema_json=json.dumps(request_schema, separators=(",", ":")) if isinstance(request_schema, dict) else "",
            request_value_schema_json=json.dumps(
                transform_schema_for_value(request_schema, request_field_map), separators=(",", ":")
            )
            if isinstance(request_schema, dict)
            else "",
            response_schema_json=json.dumps(response_schema, separators=(",", ":")) if isinstance(response_schema, dict) else "",
            response_value_schema_json=json.dumps(
                transform_schema_for_value(response_schema, response_field_map), separators=(",", ":")
            )
            if isinstance(response_schema, dict)
            else "",
            source_response_schema_json=json.dumps(
                schema_document_with_refs(source_spec, original_response_schema), separators=(",", ":")
            )
            if isinstance(original_response_schema, dict)
            else "",
            response_content_type=response.get("content_type", ""),
            response_fields=response_fields,
        )
    if not result.qualified_interface:
        raise ValueError(f"REST binding has no interface name: {path}")
    return result


def parse_rest_binding(path: Path) -> RestMetadata:
    if path.name.endswith(".rest.json"):
        return parse_json_binding(path)
    raise ValueError(f"expected .rest.json binding: {path}")


def target_from_idl_cmake(endpoint_root: Path, fallback: str) -> str:
    cmake_path = endpoint_root / "idl" / "CMakeLists.txt"
    if not cmake_path.exists():
        return fallback
    match = re.search(r"CanopyGenerate\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)", cmake_path.read_text(encoding="utf-8"))
    return match.group(1) if match else fallback


def endpoint_from_binding(binding_path: Path) -> EndpointInfo:
    endpoint_root = binding_path.parents[2]
    if binding_path.name.endswith(".rest.json"):
        idl_path = binding_path.with_name(binding_path.name[: -len(".rest.json")] + ".idl")
    else:
        raise ValueError(f"unexpected REST binding filename: {binding_path}")
    target = target_from_idl_cmake(endpoint_root, idl_path.stem)
    metadata = parse_rest_binding(binding_path)
    if not metadata.methods:
        raise ValueError("skip_no_methods")
    methods = parse_idl_methods(idl_path, metadata.qualified_interface)
    include_path = f"{idl_path.parent.name}/{idl_path.stem}.h"
    defined_types, global_types = collect_idl_type_names(idl_path)
    return EndpointInfo(
        slug=endpoint_root.name,
        target=target,
        idl_path=idl_path,
        binding_path=binding_path,
        include_path=include_path,
        metadata=metadata,
        methods=methods,
        defined_types=defined_types,
        global_types=global_types,
    )


def cxx_string(value: str) -> str:
    return json.dumps(value)


def is_json_content_type(content_type: str) -> bool:
    if not content_type:
        return True
    media_type = content_type.split(";", 1)[0].strip().lower()
    return media_type in {"application/json", "application/*+json", "*/*"} or media_type.endswith("+json")


def parse_body_field_map(value: object) -> dict:
    if not isinstance(value, str) or not value:
        return {}
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError:
        return {}
    return parsed if isinstance(parsed, dict) else {}


def transform_schema_for_value(schema: object, field_map: dict) -> object:
    if isinstance(schema, list):
        return [transform_schema_for_value(item, field_map) for item in schema]
    if not isinstance(schema, dict):
        return schema

    result = {key: transform_schema_for_value(value, field_map) for key, value in schema.items()}

    if "items" in field_map and isinstance(result.get("items"), dict):
        result["items"] = transform_schema_for_value(result["items"], field_map["items"])

    if "additionalProperties" in field_map and isinstance(result.get("additionalProperties"), dict):
        result["additionalProperties"] = transform_schema_for_value(
            result["additionalProperties"], field_map["additionalProperties"]
        )

    fields = field_map.get("fields")
    properties = result.get("properties")
    if isinstance(fields, list) and isinstance(properties, dict):
        by_wire_name = {
            field.get("wire_name", field.get("name")): field
            for field in fields
            if isinstance(field, dict) and field.get("name")
        }
        renamed_properties = {}
        for property_name, property_schema in properties.items():
            field = by_wire_name.get(property_name)
            if not field:
                renamed_properties[property_name] = property_schema
                continue
            nested_map = field.get("map")
            renamed_properties[field["name"]] = (
                transform_schema_for_value(property_schema, nested_map)
                if isinstance(nested_map, dict)
                else property_schema
            )
        result["properties"] = renamed_properties

        required = result.get("required")
        if isinstance(required, list):
            result["required"] = [
                by_wire_name[item]["name"]
                if isinstance(item, str) and item in by_wire_name
                else item
                for item in required
            ]

    for composition in ("allOf", "anyOf", "oneOf"):
        values = result.get(composition)
        if isinstance(values, list):
            result[composition] = [transform_schema_for_value(value, field_map) for value in values]

    return result


def write_if_different(path: Path, content: str) -> None:
    old = None
    try:
        old = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        pass
    if old == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def schema_include_path(include_path: str) -> str:
    path = Path(include_path)
    schema_name = f"{path.stem}_schema.h"
    if path.parent == Path("."):
        return schema_name
    return str(path.parent / schema_name).replace("\\", "/")


def namespace_parts(qualified_interface: str) -> list[str]:
    return qualified_interface.split("::")[:-1]


def open_namespaces(parts: list[str]) -> str:
    return "".join(f"namespace {part}\n{{\n" for part in parts)


def close_namespaces(parts: list[str]) -> str:
    return "".join(f"}} // namespace {part}\n" for part in reversed(parts))


def parameter_list(method: IdlMethod) -> str:
    return ", ".join(parameter.declaration for parameter in method.parameters)


def method_argument_setup(method: IdlMethod) -> tuple[list[str], list[str]]:
    lines: list[str] = []
    args: list[str] = []
    for parameter in method.parameters:
        if parameter.direction == "in":
            lines.append(f"        auto {parameter.name} = {ROUNDTRIP_NS}::sample_value<{parameter.value_type}>();")
        else:
            lines.append(f"        {parameter.value_type} {parameter.name}{{}};")
        args.append(parameter.name)
    return lines, args


def qualify_generated_type(
    type_name: str, namespace_prefix: str, defined_types: set[str], global_types: set[str]
) -> str:
    if (not namespace_prefix or not defined_types) and not global_types:
        return type_name

    def replace(match: re.Match[str]) -> str:
        token = match.group(0)
        before = type_name[: match.start()]
        after = type_name[match.end() :]
        if before.endswith("::") or after.startswith("::"):
            return token
        if token in global_types:
            return f"::{token}"
        if token not in defined_types or not namespace_prefix:
            return token
        return f"::{namespace_prefix}::{token}"

    return re.sub(r"\b[A-Za-z_][A-Za-z0-9_]*\b", replace, type_name)


def method_argument_setup_for_main(
    method: IdlMethod,
    metadata: RestMethod | None,
    namespace_prefix: str,
    defined_types: set[str],
    global_types: set[str],
) -> tuple[list[str], list[str]]:
    lines: list[str] = []
    args: list[str] = []
    for parameter in method.parameters:
        value_type = qualify_generated_type(parameter.value_type, namespace_prefix, defined_types, global_types)
        if parameter.direction == "in":
            if metadata and metadata.request_value_schema_json and metadata.body_param == parameter.name:
                lines.append(
                    f"        auto {parameter.name} = {ROUNDTRIP_NS}::sample_value_from_schema<{value_type}>("
                    f"{cxx_string(metadata.request_value_schema_json)});"
                )
            else:
                lines.append(f"        auto {parameter.name} = {ROUNDTRIP_NS}::sample_value<{value_type}>();")
        else:
            lines.append(f"        {value_type} {parameter.name}{{}};")
        args.append(parameter.name)
    return lines, args


def unique_local_name(base_name: str, method: IdlMethod) -> str:
    used_names = {parameter.name for parameter in method.parameters}
    if base_name not in used_names:
        return base_name

    suffix = 1
    while f"{base_name}_{suffix}" in used_names:
        suffix += 1
    return f"{base_name}_{suffix}"


def schema_validation_block(info: EndpointInfo, method: IdlMethod) -> str:
    metadata = info.metadata.methods.get(method.name)
    if metadata is None:
        return ""

    out_parameters = [parameter for parameter in method.parameters if parameter.direction == "out"]
    needs_function_info = (
        (bool(metadata.body_param) and not metadata.request_schema_json)
        or (bool(metadata.out_param) and not metadata.response_schema_json)
        or (bool(out_parameters) and not metadata.out_param and not metadata.response_schema_json)
    )

    lines: list[str] = []
    if needs_function_info:
        lines.extend(
            [
                f"        const auto* __function_info = {ROUNDTRIP_NS}::find_function_info<interface_type>({cxx_string(method.name)});",
                "        if (!__function_info)",
                "        {",
                f"            std::cerr << {cxx_string(method.name)} << \" schema metadata missing\\n\";",
                "            return 6;",
                "        }",
            ]
        )

    if metadata.body_param:
        if metadata.request_schema_json:
            lines.extend(
                [
                    f"        if (!{ROUNDTRIP_NS}::validate_json_body_against_schema(",
                    f"                {cxx_string(metadata.request_schema_json)}, client.stream->last_request().body,",
                    f"                {cxx_string(method.name + ' request body')}, std::cerr))",
                    "        {",
                    "            if (client.stream)",
                    f"                {ROUNDTRIP_NS}::print_last_exchange(std::cerr, *client.stream);",
                    "            return 6;",
                    "        }",
                ]
            )
        else:
            lines.extend(
                [
                    f"        if (!{ROUNDTRIP_NS}::validate_json_body_as_method_property(",
                    f"                __function_info->in_json_schema, {cxx_string(metadata.body_param)}, client.stream->last_request().body,",
                    f"                {cxx_string(method.name + ' request body')}, std::cerr))",
                    "        {",
                    "            if (client.stream)",
                    f"                {ROUNDTRIP_NS}::print_last_exchange(std::cerr, *client.stream);",
                    "            return 6;",
                    "        }",
                ]
            )

    if metadata.response_schema_json and is_json_content_type(metadata.response_content_type):
        lines.extend(
            [
                f"        if (!{ROUNDTRIP_NS}::validate_json_body_against_schema(",
                f"                {cxx_string(metadata.response_schema_json)}, client.stream->last_response_body(),",
                f"                {cxx_string(method.name + ' response body')}, std::cerr))",
                "        {",
                "            if (client.stream)",
                f"                {ROUNDTRIP_NS}::print_last_exchange(std::cerr, *client.stream);",
                "            return 6;",
                "        }",
            ]
        )
    elif metadata.out_param and is_json_content_type(metadata.response_content_type):
        lines.extend(
            [
                f"        if (!{ROUNDTRIP_NS}::validate_json_body_as_method_property(",
                f"                __function_info->out_json_schema, {cxx_string(metadata.out_param)}, client.stream->last_response_body(),",
                f"                {cxx_string(method.name + ' response body')}, std::cerr))",
                "        {",
                "            if (client.stream)",
                f"                {ROUNDTRIP_NS}::print_last_exchange(std::cerr, *client.stream);",
                "            return 6;",
                "        }",
            ]
        )
    elif out_parameters and is_json_content_type(metadata.response_content_type):
        lines.extend(
            [
                f"        if (!{ROUNDTRIP_NS}::validate_json_body_against_schema(",
                f"                __function_info->out_json_schema, client.stream->last_response_body(),",
                f"                {cxx_string(method.name + ' response body')}, std::cerr))",
                "        {",
                "            if (client.stream)",
                f"                {ROUNDTRIP_NS}::print_last_exchange(std::cerr, *client.stream);",
                "            return 6;",
                "        }",
            ]
        )

    return "\n".join(lines)


def response_field_for_parameter(metadata: RestMethod, parameter_name: str) -> RestField | None:
    for field in metadata.response_fields:
        if field.name == parameter_name:
            return field
    return None


def output_sample_expression(metadata: RestMethod | None, parameter: IdlParameter, value_type: str) -> str:
    if metadata and metadata.source_response_schema_json and "json::v1::object" in value_type:
        return (
            f"{ROUNDTRIP_NS}::sample_value_from_schema<{value_type}>("
            f"{cxx_string(metadata.source_response_schema_json)})"
        )
    if metadata and metadata.response_value_schema_json:
        if metadata.out_param == parameter.name:
            return (
                f"{ROUNDTRIP_NS}::sample_value_from_schema<{value_type}>("
                f"{cxx_string(metadata.response_value_schema_json)})"
            )
        field = response_field_for_parameter(metadata, parameter.name)
        if field is not None:
            return (
                f"{ROUNDTRIP_NS}::sample_value_from_schema_property<{value_type}>("
                f"{cxx_string(metadata.response_value_schema_json)}, {cxx_string(field.name)})"
            )
    return f"{ROUNDTRIP_NS}::sample_value<{value_type}>()"


def write_source(info: EndpointInfo, output_path: Path) -> None:
    ns_parts = namespace_parts(info.metadata.qualified_interface)
    namespace_prefix = "::".join(ns_parts)
    interface_simple = info.metadata.qualified_interface.split("::")[-1]
    interface_type = f"::{info.metadata.qualified_interface}"
    service_type = (
        f"::{namespace_prefix}::roundtrip_recording_service" if namespace_prefix else "::roundtrip_recording_service"
    )
    methods_by_name = {method.name: method for method in info.methods}
    callable_methods = [methods_by_name[name] for name in info.metadata.methods if name in methods_by_name]

    if not callable_methods:
        raise ValueError(f"no metadata methods matched IDL methods for {info.slug}")

    service_methods: list[str] = []
    for method in info.methods:
        metadata = info.metadata.methods.get(method.name)
        params = parameter_list(method)
        const_suffix = " const" if method.const_suffix else ""
        body: list[str] = []
        if method.name in info.metadata.methods:
            body.append(f"        recorded_methods.push_back({cxx_string(method.name)});")
        for parameter in method.parameters:
            if parameter.direction == "out":
                value_type = qualify_generated_type(
                    parameter.value_type, namespace_prefix, info.defined_types, info.global_types)
                body.append(f"        {parameter.name} = {output_sample_expression(metadata, parameter, value_type)};")
            else:
                body.append(f"        (void){parameter.name};")
        if method.return_type == "void":
            body.append("        CO_RETURN;")
        else:
            return_type = qualify_generated_type(method.return_type, namespace_prefix, info.defined_types, info.global_types)
            body.append(f"        CO_RETURN {ROUNDTRIP_NS}::ok_return<{return_type}>();")
        service_methods.append(
            f"    CORO_TASK({method.return_type}) {method.name}({params}){const_suffix} override\n"
            "    {\n"
            + "\n".join(body)
            + "\n    }\n"
        )

    call_blocks: list[str] = []
    expected_calls: list[str] = []
    for method in callable_methods:
        metadata = info.metadata.methods.get(method.name)
        setup_lines, args = method_argument_setup_for_main(
            method, metadata, namespace_prefix, info.defined_types, info.global_types
        )
        call_result_name = unique_local_name("call_result", method)
        result_check = (
            f"        const auto {call_result_name} = SYNC_WAIT(connected.object->{method.name}({', '.join(args)}));\n"
            f"        if (static_cast<int>({call_result_name}) != rpc::error::OK())\n"
            "        {\n"
            f"            std::cerr << {cxx_string(method.name)} << \" failed: \" << static_cast<int>({call_result_name}) << \"\\n\";\n"
            "            if (client.stream)\n"
            f"                {ROUNDTRIP_NS}::print_last_exchange(std::cerr, *client.stream);\n"
            "            return 4;\n"
            "        }"
            if method.return_type != "void"
            else f"        SYNC_WAIT(connected.object->{method.name}({', '.join(args)}));"
        )
        validation_check = schema_validation_block(info, method)
        call_blocks.append(
            "    {\n"
            + ("\n".join(setup_lines) + "\n" if setup_lines else "")
            + result_check
            + ("\n" + validation_check if validation_check else "")
            + "\n    }\n"
        )
        expected_calls.append(method.name)

    source = f"""// {GENERATED_MARKER}

#include <iostream>
#include <string>
#include <utility>
#include <vector>

#include <canopy/third_party_rest/roundtrip_test_support.h>
#include <canopy/rest/server.h>
#include <rpc/rpc.h>

#include <{info.include_path}>
#include <{schema_include_path(info.include_path)}>

{open_namespaces(ns_parts)}
class roundtrip_recording_service final : public rpc::base<roundtrip_recording_service, {interface_simple}>
{{
public:
    std::vector<std::string> recorded_methods;

{''.join(service_methods)}
}};
{close_namespaces(ns_parts)}

int main(int argc, char* argv[])
{{
    using interface_type = {interface_type};
    using service_type = {service_type};
    auto implementation = new service_type;
    rpc::shared_ptr<interface_type> object(implementation);

    canopy::rest::endpoint_registry registry;
    registry.add_object<interface_type>("roundtrip", object);
    if ({ROUNDTRIP_NS}::wants_http_server(argc, argv))
        return {ROUNDTRIP_NS}::serve_http_registry_from_cli(std::move(registry), argc, argv, {cxx_string(info.slug)});

    auto client = {ROUNDTRIP_NS}::make_loopback_client<interface_type>(
        std::move(registry), {cxx_string(info.target + "_roundtrip_loopback")});

    auto connected = SYNC_WAIT(
        interface_type::rest_caller::connect(std::move(client.settings), {{}}, std::move(client.factory_context)));
    if (connected.error_code != rpc::error::OK() || !connected.object)
    {{
        std::cerr << "connect failed: " << connected.error_code << "\\n";
        return 3;
    }}

{''.join(call_blocks)}
    const std::vector<std::string> expected_methods{{{', '.join(cxx_string(name) for name in expected_calls)}}};
    if (implementation->recorded_methods != expected_methods)
    {{
        std::cerr << "recorded method mismatch: expected " << expected_methods.size()
                  << " calls, got " << implementation->recorded_methods.size() << "\\n";
        return 5;
    }}

    if (connected.stream)
        SYNC_WAIT(connected.stream->set_closed());
    connected.object = nullptr;
    connected.stream.reset();

    std::cout << "roundtrip ok: {info.slug} ({len(expected_calls)} methods)\\n";
    return 0;
}}
"""
    write_if_different(output_path, source)


def cmake_block(info: EndpointInfo) -> str:
    target = info.target
    test_target = f"{target}_roundtrip_test"
    return f"""{BEGIN_CMAKE_MARKER}
if((DEFINED CANOPY_BUILD_TEST AND CANOPY_BUILD_TEST) OR (DEFINED BUILD_TEST AND BUILD_TEST))
  add_executable({test_target} src/{test_target}.cpp)
  target_compile_definitions({test_target} PRIVATE ${{CANOPY_DEFINES}})
  target_include_directories({test_target} PRIVATE ${{CANOPY_INCLUDES}} ${{CMAKE_CURRENT_LIST_DIR}}/../include)
  target_compile_options({test_target} PRIVATE ${{CANOPY_COMPILE_OPTIONS}} ${{CANOPY_WARN_OK}})
  target_link_options({test_target} PRIVATE ${{CANOPY_LINK_EXE_OPTIONS}})
  target_link_libraries(
    {test_target}
    PRIVATE {target}_idl
            json_idl
            rest
            rpc::modules
            rpc
            rpc_log
            ${{CANOPY_LIBRARIES}})
  set_property(GLOBAL APPEND PROPERTY CANOPY_THIRD_PARTY_REST_ROUNDTRIP_TEST_TARGETS {test_target})
  add_test(NAME {test_target} COMMAND {test_target})
endif()
{END_CMAKE_MARKER}
"""


def ensure_endpoint_idl_cmake(info: EndpointInfo) -> None:
    idl_root = info.binding_path.parents[1]
    cmake_path = idl_root / "CMakeLists.txt"
    if cmake_path.exists():
        return

    content = f"""cmake_minimum_required(VERSION 3.24)

# Generated by tools/generate_rest_roundtrip_tests.py
CanopyGenerate(
  {info.target}
  {info.idl_path.parent.name}/{info.idl_path.name}
  ${{CMAKE_CURRENT_LIST_DIR}}
  ${{CMAKE_BINARY_DIR}}/generated
  ""
  yas_binary
  yas_json
  rest_client ${{CMAKE_CURRENT_LIST_DIR}}/{info.binding_path.parent.name}/{info.idl_path.stem}.openapi.json
  dependencies rpc_types_idl json_idl
  include_paths ${{CMAKE_CURRENT_LIST_DIR}} ${{CANOPY_INTERFACE_SOURCE_DIR}}
  install_dir ${{GENERATED_INSTALL_DIR}})
"""
    write_if_different(cmake_path, content)


def update_endpoint_cmake(info: EndpointInfo) -> None:
    cmake_path = info.binding_path.parents[2] / "CMakeLists.txt"
    text = cmake_path.read_text(encoding="utf-8") if cmake_path.exists() else "cmake_minimum_required(VERSION 3.24)\n\nadd_subdirectory(idl)\n"
    block = cmake_block(info)
    pattern = re.compile(re.escape(BEGIN_CMAKE_MARKER) + r".*?" + re.escape(END_CMAKE_MARKER) + r"\n?", re.S)
    if pattern.search(text):
        text = pattern.sub(block, text)
    else:
        if not text.endswith("\n"):
            text += "\n"
        text += "\n" + block
    write_if_different(cmake_path, text)


def discover_bindings(rest_root: Path, slugs: list[str]) -> list[Path]:
    def endpoint_bindings(endpoint_root: Path) -> list[Path]:
        return sorted(endpoint_root.glob("idl/*/*.rest.json"))

    if slugs:
        paths: list[Path] = []
        for slug in slugs:
            paths.extend(endpoint_bindings(rest_root / slug))
        return paths
    paths = []
    for endpoint_root in sorted(path for path in rest_root.iterdir() if path.is_dir()):
        paths.extend(endpoint_bindings(endpoint_root))
    return paths


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rest-root", type=Path, default=REST_ROOT)
    parser.add_argument("--manifest", type=Path, default=None)
    parser.add_argument("--slug", action="append", default=[])
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    rest_root = args.rest_root.resolve()
    manifest_path = (args.manifest or rest_root / "roundtrip_manifest.json").resolve()
    entries = []
    for binding_path in discover_bindings(rest_root, args.slug):
        entry = {"slug": binding_path.parents[2].name, "rest_binding": str(binding_path)}
        try:
            info = endpoint_from_binding(binding_path)
            source_path = binding_path.parents[2] / "src" / f"{info.target}_roundtrip_test.cpp"
            entry.update(
                {
                    "status": "dry_run" if args.dry_run else "written",
                    "target": info.target,
                    "test_target": f"{info.target}_roundtrip_test",
                    "test_source": str(source_path),
                    "qualified_interface": info.metadata.qualified_interface,
                    "methods": len(info.metadata.methods),
                    "http_methods": sorted({method.http_method.upper() for method in info.metadata.methods.values()}),
                }
            )
            if not args.dry_run:
                ensure_endpoint_idl_cmake(info)
                write_source(info, source_path)
                update_endpoint_cmake(info)
        except Exception as exc:
            if str(exc) == "skip_no_methods":
                entry.update({"status": "skipped_no_methods", "methods": 0, "http_methods": []})
            else:
                entry.update({"status": "failed", "error": str(exc)})
        entries.append(entry)

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    method_counts = Counter()
    for entry in entries:
        if entry.get("status") not in ("written", "dry_run"):
            continue
        for method in entry.get("http_methods", []):
            method_counts[method] += 1
    write_if_different(
        manifest_path,
        json.dumps({"http_method_endpoint_coverage": dict(sorted(method_counts.items())), "entries": entries}, indent=2)
        + "\n",
    )
    written = sum(1 for entry in entries if entry["status"] in ("written", "dry_run"))
    failed = sum(1 for entry in entries if entry["status"] == "failed")
    skipped = sum(1 for entry in entries if entry["status"] == "skipped_no_methods")
    coverage = ", ".join(f"{method}={count}" for method, count in sorted(method_counts.items()))
    print(f"roundtrip generation: {written} usable, {skipped} skipped, {failed} failed; manifest: {manifest_path}")
    if coverage:
        print(f"http method endpoint coverage: {coverage}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
