#!/usr/bin/env python3
#
# Copyright (c) 2026 Edward Boggis-Rolfe
# All rights reserved.

"""Generate endpoint-owned smoke tests for third-party REST connector probes.

The common path is one or two services:

    python3 tools/generate_rest_connect_smokes.py --slug airportsapi

Generated files are written beside each service:

    third_party_interfaces/rest/<slug>/idl/<slug>/<target>.idl
    third_party_interfaces/rest/<slug>/idl/<slug>/<target>.rest.json
    third_party_interfaces/rest/<slug>/idl/CMakeLists.txt
    third_party_interfaces/rest/<slug>/src/<target>_test.cpp
    third_party_interfaces/rest/<slug>/CMakeLists.txt

With no filters the tool sweeps the whole third-party REST corpus, which is useful
for stress-testing the generator rather than day-to-day client work.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from urllib.error import URLError
from urllib.parse import urlparse
from urllib.request import Request, urlopen


ROOT = Path(__file__).resolve().parents[1]
CONVERTER = ROOT / "tools" / "openapi_to_canopy_idl.py"
GENERATED_MARKER = "Generated by tools/generate_rest_connect_smokes.py"


def safe_identifier(value: str) -> str:
    value = re.sub(r"[^0-9A-Za-z_]+", "_", value).strip("_").lower()
    value = re.sub(r"_+", "_", value)
    if not value:
        value = "api"
    if value[0].isdigit():
        value = f"api_{value}"
    return value


def endpoint_target_name(slug: str, source: dict) -> str:
    configured = source.get("canopy_target")
    if isinstance(configured, str) and configured:
        return safe_identifier(configured)
    return safe_identifier(slug)


def endpoint_idl_dir_name(endpoint_root: Path, slug: str, target: str) -> str:
    slug_dir = endpoint_root / "idl" / slug
    if (slug_dir / f"{target}.openapi.json").exists() or (slug_dir / f"{target}.idl").exists():
        return slug
    target_dir = endpoint_root / "idl" / target
    if (target_dir / f"{target}.openapi.json").exists() or (target_dir / f"{target}.idl").exists():
        return target
    existing_specs = sorted((endpoint_root / "idl").glob("*/*.openapi.json"))
    if len(existing_specs) == 1:
        return existing_specs[0].parent.name
    return target


def json_load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def write_bytes_if_different(path: Path, data: bytes) -> None:
    old = None
    try:
        old = path.read_bytes()
    except FileNotFoundError:
        pass
    if old == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def read_spec(url: str, timeout: float, max_bytes: int) -> bytes:
    parsed = urlparse(url)
    if parsed.scheme in ("", "file"):
        path = Path(parsed.path if parsed.scheme == "file" else url)
        data = path.read_bytes()
    else:
        request = Request(
            url,
            headers={
                "Accept": "application/json, */*",
                "User-Agent": "Canopy REST connector smoke generator",
            },
        )
        with urlopen(request, timeout=timeout) as response:
            data = response.read(max_bytes + 1)
    if len(data) > max_bytes:
        raise ValueError(f"spec exceeds {max_bytes} byte limit")
    return data


def candidate_urls(source: dict) -> list[str]:
    urls = []
    for key in ("spec_url", "source_url"):
        value = source.get(key)
        if isinstance(value, str) and value and value not in urls:
            urls.append(value)
    return urls


def parse_rest_binding(path: Path) -> dict:
    if path.name.endswith(".rest.json"):
        value = json.loads(path.read_text(encoding="utf-8"))
        interfaces = value.get("interfaces")
        if not isinstance(interfaces, list) or not interfaces:
            raise ValueError(f"REST binding has no interfaces: {path}")
        interface = interfaces[0]
        methods = interface.get("methods", [])
        return {
            "interface": interface.get("qualified_name", ""),
            "host": interface.get("host", ""),
            "base_path": interface.get("base_path", ""),
            "methods": len(methods) if isinstance(methods, list) else 0,
        }

    raise ValueError(f"expected .rest.json binding: {path}")


def is_generated_idl(path: Path) -> bool:
    if not path.exists():
        return False
    return "by openapi_to_canopy_idl.py" in path.read_text(encoding="utf-8", errors="replace")[:512]


def is_generated_connect_source(path: Path) -> bool:
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="replace")
    if GENERATED_MARKER in text[:512]:
        return True
    return (
        "#include <canopy/rest/connection.h>" in text
        and "::rest_caller::connect" in text
        and "rpc::root_service::create(" in text
        and "connect ok:" in text
    )


def generated_artifact_stem(path: Path) -> str:
    for suffix in (".openapi.json", ".swagger.json", ".rest.json", ".idl"):
        if path.name.endswith(suffix):
            return path.name[: -len(suffix)]
    return path.stem


def build_connect_entry(
    entry: dict,
    idl_path: Path,
    binding_path: Path,
    spec_path: Path | None,
    endpoint_root: Path,
    args: argparse.Namespace,
    status: str,
) -> dict:
    metadata = parse_rest_binding(binding_path)
    idl_cmake = endpoint_root / "idl" / "CMakeLists.txt"
    entry.update(
        {
            "status": status,
            "idl": str(idl_path),
            "rest_binding": str(binding_path),
            "endpoint_cmake": str(endpoint_root / "CMakeLists.txt"),
            "idl_cmake": str(idl_cmake),
            "root_cmake_status": "existing_unmodified" if (endpoint_root / "CMakeLists.txt").exists() else "missing",
            "idl_cmake_status": "existing_unmodified" if idl_cmake.exists() else "missing",
            "idl_cmake_consumable": idl_cmake.exists(),
            "qualified_interface": metadata["interface"],
            "host": metadata["host"],
            "base_path": metadata["base_path"],
            "methods": metadata["methods"],
            "include_dir": idl_path.parent.name,
            "uses_json_fallback": "json::v1::object" in idl_path.read_text(encoding="utf-8"),
        }
    )
    if spec_path is not None:
        entry["openapi_json"] = str(spec_path)
    if metadata["methods"] == 0:
        entry["status"] = f"{status}_no_methods"
        return entry

    source_root = endpoint_root / "src"
    source_root.mkdir(parents=True, exist_ok=True)
    source_file = source_root / f"{entry['target']}_test.cpp"
    if source_file.exists() and not is_generated_connect_source(source_file):
        entry["test_source_status"] = "existing_unmodified"
    else:
        write_connect_source(source_file, entry, args.connect_timeout_ms, args.receive_timeout_ms)
        entry["test_source_status"] = "written"
    entry["test_source"] = str(source_file)
    entry["test_target"] = f"{entry['target']}_test"
    return entry


def write_connect_source(path: Path, entry: dict, connect_timeout_ms: int, receive_timeout_ms: int) -> None:
    interface = entry["qualified_interface"]
    include_dir = entry["include_dir"]
    target = entry["target"]
    slug = entry["slug"]
    host = entry["host"]
    base_path = entry["base_path"]
    path.write_text(
        f"""// {GENERATED_MARKER}

#include <chrono>
#include <iostream>
#include <memory>

#include <canopy/rest/connection.h>
#include <rpc/rpc.h>
#include <streaming/stream.h>

#include <{include_dir}/{target}.h>

int main()
{{
    using interface_type = ::{interface};
    auto executor = rpc::make_executor();
    auto service = rpc::root_service::create("{target}", rpc::zone{{rpc::DEFAULT_PREFIX}}, executor);

    interface_type::rest_settings settings;
    settings.connect_timeout = std::chrono::milliseconds{{{connect_timeout_ms}}};
    settings.receive_timeout = std::chrono::milliseconds{{{receive_timeout_ms}}};

    auto connected = SYNC_WAIT(interface_type::rest_caller::connect(std::move(settings), service));
    const auto error = connected.error_code;
    if (connected.stream)
        SYNC_WAIT(connected.stream->set_closed());
    connected.object = nullptr;
    connected.stream.reset();
    service.reset();
    rpc::shutdown_executor(executor);

    if (error != rpc::error::OK())
    {{
        std::cerr << "connect failed: " << error << "\\n";
        return 2;
    }}
    std::cout << "connect ok: {slug} -> {host}{base_path}\\n";
    return 0;
}}
""",
        encoding="utf-8",
        newline="\n",
    )


def write_endpoint_idl_cmake(endpoint_root: Path, slug: str, target: str, idl_dir_name: str) -> tuple[str, bool]:
    idl_root = endpoint_root / "idl"
    cmake_path = idl_root / "CMakeLists.txt"
    generated_marker = f"# {GENERATED_MARKER}"
    if cmake_path.exists() and generated_marker not in cmake_path.read_text(encoding="utf-8"):
        return "existing_unmodified", True

    idl_root.mkdir(parents=True, exist_ok=True)
    cmake_path.write_text(
        f"""cmake_minimum_required(VERSION 3.24)

{generated_marker}
CanopyGenerate(
  {target}
  {idl_dir_name}/{target}.idl
  ${{CMAKE_CURRENT_LIST_DIR}}
  ${{CMAKE_BINARY_DIR}}/generated
  ""
  yas_binary
  yas_json
  rest_client ${{CMAKE_CURRENT_LIST_DIR}}/{idl_dir_name}/{target}.openapi.json
  dependencies rpc_types_idl json_idl
  include_paths ${{CMAKE_CURRENT_LIST_DIR}} ${{CANOPY_INTERFACE_SOURCE_DIR}}
  install_dir ${{GENERATED_INSTALL_DIR}})
""",
        encoding="utf-8",
        newline="\n",
    )
    return "written", True


def write_endpoint_root_cmake(endpoint_root: Path, target: str) -> str:
    cmake_path = endpoint_root / "CMakeLists.txt"
    if cmake_path.exists():
        return "existing_unmodified"

    cmake_path.write_text(
        f"""cmake_minimum_required(VERSION 3.24)

# Generated by tools/generate_rest_connect_smokes.py
if(CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
  project(
    {target}_canopy
    VERSION 1.0.0
    LANGUAGES C CXX)

  set(CANOPY_BUILD_TEST OFF CACHE BOOL "")
  set(CANOPY_BUILD_RUST OFF CACHE BOOL "" FORCE)
  set(CANOPY_BUILD_DEMOS OFF CACHE BOOL "" FORCE)
  set(CANOPY_BUILD_BENCHMARKING OFF CACHE BOOL "" FORCE)
  set(CANOPY_BUILD_PROTOCOL_BUFFERS OFF CACHE BOOL "" FORCE)
  set(CANOPY_BUILD_NANOPB OFF CACHE BOOL "" FORCE)

  get_filename_component(CANOPY_SOURCE_DIR "${{CMAKE_CURRENT_LIST_DIR}}/../../.." ABSOLUTE)
  add_subdirectory("${{CANOPY_SOURCE_DIR}}" "${{CMAKE_BINARY_DIR}}/canopy_build")

  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${{CMAKE_BINARY_DIR}}/output)
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${{CMAKE_BINARY_DIR}}/output)
  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${{CMAKE_BINARY_DIR}}/output)
endif()

add_subdirectory(idl)

if((DEFINED CANOPY_BUILD_TEST AND CANOPY_BUILD_TEST) OR (DEFINED BUILD_TEST AND BUILD_TEST))
  add_executable({target}_test src/{target}_test.cpp)
  target_compile_definitions({target}_test PRIVATE ${{CANOPY_DEFINES}})
  target_include_directories({target}_test PRIVATE ${{CANOPY_INCLUDES}})
  target_compile_options({target}_test PRIVATE ${{CANOPY_COMPILE_OPTIONS}} ${{CANOPY_WARN_OK}})
  target_link_options({target}_test PRIVATE ${{CANOPY_LINK_EXE_OPTIONS}})
  target_link_libraries(
    {target}_test
    PRIVATE {target}_idl
            json_idl
            rest
            rpc::modules
            rpc
            rpc_log
            ${{CANOPY_LIBRARIES}})
endif()
""",
        encoding="utf-8",
        newline="\n",
    )
    return "written"


def clean_generated_endpoint_files(
    endpoint_root: Path, slug: str, target: str, idl_dir_name: str | None = None, *, clean_cmake: bool = True
) -> None:
    generated_marker = f"# {GENERATED_MARKER}"
    idl_root = endpoint_root / "idl"
    cmake_path = idl_root / "CMakeLists.txt"
    if clean_cmake and cmake_path.exists() and generated_marker in cmake_path.read_text(encoding="utf-8"):
        cmake_path.unlink()

    generated_dir = idl_root / (idl_dir_name or target)
    if not generated_dir.exists():
        return
    keep = {
        f"{target}.idl",
        f"{target}.openapi.json",
        f"{target}.rest.json",
    }
    generated_stems = {
        path.stem
        for path in generated_dir.iterdir()
        if path.is_file() and path.name.endswith(".idl") and is_generated_idl(path)
    }
    for path in generated_dir.iterdir():
        if not path.is_file() or path.name in keep:
            continue
        stem = generated_artifact_stem(path)
        if stem in generated_stems:
            path.unlink()


def write_manifest(
    manifest_path: Path,
    rest_root: Path,
    entries: list[dict],
) -> None:
    build_entries = [
        entry
        for entry in entries
        if entry.get("status") in ("converted", "existing_idl") and entry.get("methods", 0) > 0
    ]
    report = {
        "rest_root": str(rest_root),
        "generated_layout": "endpoint_idl_and_endpoint_tests",
        "count": len(entries),
        "build_count": len(build_entries),
        "entries": entries,
    }
    manifest_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")


def selected_sources(rest_root: Path, slugs: list[str], source_jsons: list[Path]) -> list[Path]:
    sources: list[Path] = []
    for slug in slugs:
        sources.append(rest_root / slug / "source.json")
    sources.extend(source_jsons)
    if not sources:
        sources = sorted(rest_root.glob("*/source.json"))
    return [source.resolve() for source in sources]


def configured_overlay_path(source: dict, endpoint_root: Path, out_dir: Path, target: str) -> Path | None:
    raw_overlay = source.get("canopy_overlay")
    if isinstance(raw_overlay, str) and raw_overlay:
        overlay_path = Path(raw_overlay)
        if not overlay_path.is_absolute():
            overlay_path = endpoint_root / overlay_path
        return overlay_path

    overlay_path = out_dir / f"{target}.canopy.overlay.json"
    return overlay_path if overlay_path.exists() else None


def convert_one(
    source_path: Path,
    args: argparse.Namespace,
    used_targets: set[str],
) -> dict:
    source = json_load(source_path)
    endpoint_root = source_path.parent
    slug = endpoint_root.name
    target_base = endpoint_target_name(slug, source)
    target = target_base
    suffix = 2
    while target in used_targets:
        target = f"{target_base}_{suffix}"
        suffix += 1
    used_targets.add(target)

    entry = {"slug": slug, "source_json": str(source_path), "target": target, "status": "pending"}

    idl_dir_name = endpoint_idl_dir_name(endpoint_root, slug, target)
    out_dir = endpoint_root / "idl" / idl_dir_name
    spec_path = out_dir / f"{target}.openapi.json"
    idl_path = out_dir / f"{target}.idl"
    binding_path = out_dir / f"{target}.rest.json"
    overlay_path = configured_overlay_path(source, endpoint_root, out_dir, target)
    clean_generated_endpoint_files(endpoint_root, slug, target, idl_dir_name, clean_cmake=False)
    if (
        not args.regenerate_existing
        and idl_path.exists()
        and binding_path.exists()
        and not is_generated_idl(idl_path)
    ):
        idl_cmake_status, idl_cmake_consumable = write_endpoint_idl_cmake(endpoint_root, slug, target, idl_dir_name)
        root_cmake_status = write_endpoint_root_cmake(endpoint_root, target)
        build_connect_entry(
            entry,
            idl_path,
            binding_path,
            spec_path if spec_path.exists() else None,
            endpoint_root,
            args,
            "existing_idl",
        )
        entry["root_cmake_status"] = root_cmake_status
        entry["idl_cmake_status"] = idl_cmake_status
        entry["idl_cmake_consumable"] = idl_cmake_consumable
        return entry

    if source.get("spec_format") not in ("OpenAPI/Swagger", "OpenAPI", "Swagger"):
        entry["status"] = "skipped_non_openapi"
        entry["error"] = f"spec_format is {source.get('spec_format')!r}"
        return entry

    spec_data = None
    spec_error = ""
    if spec_path.exists() and not args.refresh_spec:
        spec_data = spec_path.read_bytes()
        entry["spec_url"] = str(spec_path)
        entry["spec_source"] = "existing_openapi_json"
    else:
        for url in candidate_urls(source):
            try:
                spec_data = read_spec(url, args.fetch_timeout, args.max_spec_bytes)
                entry["spec_url"] = url
                entry["spec_source"] = "fetched"
                break
            except (OSError, ValueError, URLError) as exc:
                spec_error = f"{url}: {exc}"
    if spec_data is None:
        entry["status"] = "spec_fetch_failed"
        entry["error"] = spec_error or "no spec_url/source_url"
        return entry

    clean_generated_endpoint_files(endpoint_root, slug, target, idl_dir_name)
    out_dir.mkdir(parents=True, exist_ok=True)
    write_bytes_if_different(spec_path, spec_data)

    command = [
        sys.executable,
        str(CONVERTER),
        "--input",
        str(spec_path),
        "--output",
        str(idl_path),
        "--binding",
        str(binding_path),
    ]
    if overlay_path is not None:
        if not overlay_path.exists():
            entry["status"] = "overlay_missing"
            entry["error"] = f"configured canopy_overlay does not exist: {overlay_path}"
            return entry
        command.extend(["--overlay", str(overlay_path)])
        entry["canopy_overlay"] = str(overlay_path)
    if args.strict_composition:
        command.append("--strict-composition")
    completed = subprocess.run(command, text=True, capture_output=True, timeout=args.convert_timeout, check=False)
    if completed.returncode != 0:
        entry["status"] = "convert_failed"
        entry["error"] = (completed.stderr or completed.stdout).strip()
        return entry

    idl_cmake_status, idl_cmake_consumable = write_endpoint_idl_cmake(endpoint_root, slug, target, idl_dir_name)
    root_cmake_status = write_endpoint_root_cmake(endpoint_root, target)
    build_connect_entry(entry, idl_path, binding_path, spec_path, endpoint_root, args, "converted")
    entry["root_cmake_status"] = root_cmake_status
    entry["idl_cmake_status"] = idl_cmake_status
    entry["idl_cmake_consumable"] = idl_cmake_consumable
    return entry


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rest-root", type=Path, default=ROOT / "third_party_interfaces" / "rest")
    parser.add_argument("--manifest", type=Path, default=None)
    parser.add_argument("--slug", action="append", default=[], help="third_party_interfaces/rest/<slug> to generate")
    parser.add_argument("--source-json", action="append", type=Path, default=[], help="explicit source.json path")
    parser.add_argument("--fetch-timeout", type=float, default=20.0)
    parser.add_argument("--convert-timeout", type=float, default=60.0)
    parser.add_argument("--max-spec-bytes", type=int, default=64 * 1024 * 1024)
    parser.add_argument("--connect-timeout-ms", type=int, default=5000)
    parser.add_argument("--receive-timeout-ms", type=int, default=5000)
    parser.add_argument("--strict-composition", action="store_true")
    parser.add_argument("--regenerate-existing", action="store_true", help="overwrite existing non-generated endpoint IDL files")
    parser.add_argument("--refresh-spec", action="store_true", help="fetch provider specs even when a local OpenAPI copy exists")
    args = parser.parse_args()

    rest_root = args.rest_root.resolve()
    manifest_path = (args.manifest or rest_root / "connect_manifest.json").resolve()
    manifest_path.parent.mkdir(parents=True, exist_ok=True)

    entries = []
    used_targets: set[str] = set()
    sources = selected_sources(rest_root, args.slug, args.source_json)
    for index, source_path in enumerate(sources, start=1):
        print(f"[{index}/{len(sources)}] {source_path.parent.name}", file=sys.stderr, flush=True)
        try:
            entry = convert_one(source_path, args, used_targets)
        except subprocess.TimeoutExpired as exc:
            entry = {
                "slug": source_path.parent.name,
                "source_json": str(source_path),
                "status": "convert_timeout",
                "error": str(exc),
            }
        except Exception as exc:
            entry = {
                "slug": source_path.parent.name,
                "source_json": str(source_path),
                "status": "internal_error",
                "error": str(exc),
            }
        entries.append(entry)
        print(f"[{index}/{len(sources)}] {source_path.parent.name}: {entry['status']}", file=sys.stderr, flush=True)
        write_manifest(manifest_path, rest_root, entries)

    build_entries = [
        entry
        for entry in entries
        if entry.get("status") in ("converted", "existing_idl") and entry.get("methods", 0) > 0
    ]
    write_manifest(manifest_path, rest_root, entries)

    summary: dict[str, int] = {}
    for entry in entries:
        summary[entry["status"]] = summary.get(entry["status"], 0) + 1
    print(json.dumps({"count": len(entries), "build_count": len(build_entries), "summary": summary}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
