/*
 *   Copyright (c) 2026 Edward Boggis-Rolfe
 *   All rights reserved.
 */

#import "rpc/rpc_types.idl"

namespace rpc
{
    struct log_record
    {
        uint64_t level;
        std::string message;
    };
}
