name: Run CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: fedora:43
    steps:
      - name: Install dependencies
        run: |
          dnf install -y gcc gcc-c++ clang openssl-devel wget make perl-core zlib-devel ninja-build nodejs clang-tools-extra gdb python3-pip liburing-devel git
          pip install cmakelang --root-user-action=ignore --no-cache-dir --break-system-packages
          wget -q https://github.com/Kitware/CMake/releases/download/v4.3.0/cmake-4.3.0-linux-x86_64.sh
          chmod +x cmake-4.3.0-linux-x86_64.sh
          ./cmake-4.3.0-linux-x86_64.sh --skip-license --prefix=/usr/local
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check CMake formatting
        run: |
          cmake-format --version
          git ls-files -- \*.cmake \*CMakeLists.txt | xargs cmake-format --check
      - name: Check clang formatting
        run: |
          if [ -n "${{github.event.pull_request.base.sha}}" ]
          then
            changed=$(git diff --name-only "${{github.event.pull_request.base.sha}}" HEAD | grep -E '\.(cpp|h|hpp|c)$' || true)
            if [ -n "$changed" ]
            then
              if ! echo "$changed" | xargs clang-format --dry-run --Werror
              then
                echo "incorrect formatting"
                exit 1
              fi
            fi
          fi
      - name: CMake configure (Debug)
        run: cmake -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ --preset=Debug
      - name: Build (Debug)
        run: cmake --build build_debug
      - name: Test RPC (Debug)
        working-directory: build_debug/output
        run: ./rpc_test
      - name: Test Serialiser (Debug)
        working-directory: build_debug/output
        run: ./serialiser_test
      - name: Test JSON Schema Metadata (Debug)
        working-directory: build_debug/output
        run: ./json_schema_metadata_test
      - name: CMake configure (Release)
        run: cmake -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ --preset=Release
      - name: Build (Release)
        run: cmake --build build_release
      - name: Test RPC (Release)
        working-directory: build_release/output
        run: ./rpc_test
      - name: CMake configure (Coroutine Debug)
        run: cmake -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ --preset=Coroutine_Debug
      - name: Build (Coroutine Debug)
        run: cmake --build build_coroutine_debug
      - name: Test RPC (Coroutine Debug)
        working-directory: build_coroutine_debug/output
        run: ./rpc_test
      - name: CMake configure (Coroutine Release)
        run: cmake -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ --preset=Release_with_coroutines_no_logging
      - name: Build (Coroutine Release)
        run: cmake --build build_coroutine_release
      - name: Test RPC (Coroutine Release)
        working-directory: build_coroutine_release/output
        run: ./rpc_test
      - name: Test Serialiser (Coroutine Release)
        working-directory: build_coroutine_release/output
        run: ./serialiser_test
